In [8]:
from pathlib import Path
import os

#data = Path('d:\\Coding\\learndl\\learndl\\src\\configs\\fmp\\default.yaml')
#list(os.walk(data))
directory = Path('./data/ModelHidden')
[Path(dirpath).joinpath(filename) for dirpath, _, filenames in os.walk(directory) for filename in filenames][-1].stem

'hidden.1.swalast.20230606'

In [13]:
from pathlib import Path
import os

p = Path('d:/Coding/learndl/learndl/src/configs/fmp/default.yaml')
q = Path('d:/Coding/learndl/learndl/src/configs/fmp/default.yaml')
p.match(f'*default*.yaml')

True

In [1]:
from src.model.boost import GeneralBooster

In [2]:
inputs = GeneralBooster.df_input()
inputs

{'train':                  Amount_20D_Avg  Amount_240D_Avg  Asset_LR  Asset_LR_Gr  \
 date     secid                                                            
 20211029 1             0.875544         0.875703  0.375270     0.775000   
          2             0.993958         0.994373  0.994009     0.516299   
          4             0.755437         0.861125  0.301701     0.438971   
          5             0.181489         0.158951  0.389648     0.067157   
          6             0.166022         0.183120  0.246585     0.946078   
 ...                         ...              ...       ...          ...   
 20230831 871970        0.010362         0.010567  0.030890     0.458824   
          871981        0.028687         0.030800  0.077007     0.230937   
          872925        0.029014         0.025629  0.018490     0.662309   
          873169        0.025742         0.055755  0.021101     0.489107   
          873223        0.029668         0.074978  0.037198     0.037473   
 
 

In [3]:
model1 = GeneralBooster('lgbm',**inputs).fit()
model2 = GeneralBooster('ada',**inputs).fit()

Round: 1, Est-Err: 0.4939, F_name: OCFA_Resd
Round: 2, Est-Err: 0.4960, F_name: Amount_20D_Avg
Round: 3, Est-Err: 0.4986, F_name: CL
Round: 4, Est-Err: 0.4992, F_name: OCFA_Para
Round: 5, Est-Err: 0.4992, F_name: BuyMinusSell_5D_Vol
Round: 6, Est-Err: 0.4985, F_name: Rating_R3M
Round: 7, Est-Err: 0.4995, F_name: Equity_LR_Gr
Round: 8, Est-Err: 0.4996, F_name: Num_Emp
Round: 9, Est-Err: 0.4997, F_name: BuyMinusSell_5D_Amount
Round: 10, Est-Err: 0.4990, F_name: OCFA_Resd
Round: 11, Est-Err: 0.4997, F_name: EPS_FY0_R1M
Round: 12, Est-Err: 0.4998, F_name: CloseTrend_240D_Reg
Round: 13, Est-Err: 0.4998, F_name: BuyMinusSell_5D_Vol
Round: 14, Est-Err: 0.4997, F_name: Bias_5D
Round: 15, Est-Err: 0.4998, F_name: ILLIQ_240D
Round: 16, Est-Err: 0.4998, F_name: NetProfitDeducted_SQ_YoY
Round: 17, Est-Err: 0.4998, F_name: MarketCap
Round: 18, Est-Err: 0.4998, F_name: BuyMinusSell_5D_Amount
Round: 19, Est-Err: 0.4997, F_name: FloatCap
Round: 20, Est-Err: 0.4998, F_name: IVR_20D
Round: 21, Est-Err: 

In [4]:
model2 = GeneralBooster('ada',**inputs)

In [5]:
model2.booster.data['train'].X()

tensor([[0.8755, 0.8757, 0.3753,  ..., 0.0747, 0.8754, 0.7754],
        [0.9211, 0.8758, 0.3747,  ..., 0.1753, 0.9739, 0.8681],
        [0.8757, 0.8762, 0.3748,  ..., 0.0756, 0.9757, 0.5760],
        ...,
        [0.0353, 0.0854, 0.0412,  ..., 0.3083, 0.0114, 0.9901],
        [0.0379, 0.0791, 0.0408,  ..., 0.4471, 0.0391, 0.9704],
        [0.0297, 0.0750, 0.0372,  ..., 0.2218, 0.0049, 0.8052]],
       dtype=torch.float64)

In [6]:
self = model2.booster

In [7]:
import torch
from src.algo.boost import BoosterInput

In [8]:
from src.algo.boost.model.ada import StrongLearner

In [9]:


train = self.data['train']
valid = self.data['valid']

device = torch.device('cuda:0' if torch.cuda.is_available() and self.cuda else 'cpu')
train_data = BoosterInput.concat([train , valid])
x , y , w = train_data.XYW(device)

x = self.input_transform(x)
y = self.label_transform(y)

idx = (y != 0).squeeze()
x , y , w = x[idx] , y[idx] , w[idx]


In [10]:

self.model : StrongLearner = StrongLearner(**self.train_param)
self.model.fit(x , y , w , silence = False , feature = train_data.feature)

tensor([[0.4966, 0.4983, 0.4999,  ..., 0.4998, 0.4989, 0.4997],
        [0.4966, 0.4983, 0.4999,  ..., 0.4998, 0.4989, 0.4997],
        [0.4966, 0.4983, 0.4999,  ..., 0.4998, 0.4989, 0.4997],
        ...,
        [0.4966, 0.4983, 0.4999,  ..., 0.4998, 0.4989, 0.4997],
        [0.4966, 0.4983, 0.4999,  ..., 0.4998, 0.4989, 0.4997],
        [0.4966, 0.4983, 0.4999,  ..., 0.4998, 0.4989, 0.4997]])
tensor(87)
tensor([-0.1078, -0.1299, -0.1532, -0.1492, -0.0975, -0.0926, -0.2004, -0.1015,
        -0.1528, -0.1478, -0.0877, -0.1673, -0.2075, -0.1547, -0.1217, -0.2157,
        -0.1828, -0.1799, -0.2018, -0.1841])


TypeError: unsupported format string passed to Tensor.__format__

In [14]:
self.model[0].feat_losses.nan_to_num(1).min()

tensor(0.4939)

In [21]:
feature = train_data.feature

In [26]:
learner = self.model.weak_learners[0]

In [28]:
learner.bin_predictions

tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [83]:
self = learner
weight = w
X = x
from torch import Tensor

if weight is None: weight = torch.ones_like(y) / len(y)
assert isinstance(X , Tensor) and isinstance(y , Tensor) and isinstance(weight , Tensor) , (X , y , weight)
assert torch.all(X < self.n_bins) , X.max()
assert not torch.is_floating_point(X) , X
self.n_feat = X.shape[-1]

pos_wgt , neg_wgt = (weight * (y > 0))[:,None] , (weight * (y < 0))[:,None]
pos_imp = torch.zeros(self.n_feat , self.n_bins + 1).to(y)
neg_imp = pos_imp * 0.

for ibin in range(self.n_bins + 1):
    where = X == ibin - 1
    pos_imp[:,ibin] = (pos_wgt * where).sum(dim = 0)
    neg_imp[:,ibin] = (neg_wgt * where).sum(dim = 0)

feat_imp = (pos_imp + neg_imp).sum(-1,keepdim=True)
nan_ratio = (pos_imp + neg_imp)[:,0]
pos_imp , neg_imp = pos_imp / feat_imp , neg_imp / feat_imp

self.feat_losses = torch.sqrt(pos_imp * neg_imp).sum(1).nan_to_num(torch.inf).where(nan_ratio <= 0.8 , torch.inf)
self.feat_idx = self.feat_losses.argmin()
self.bin_predictions = 0.5 * torch.log((pos_imp[self.feat_idx] + self.EPS) / (neg_imp[self.feat_idx] + self.EPS))

In [100]:
((pos_imp + neg_imp)[:,0] > 0.80).argwhere()

tensor([[ 45],
        [ 46],
        [159]])

In [85]:
feature[87]

'OCFA_Resd'

In [92]:
feat_imp

tensor([[1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1

In [84]:
pos_imp[87] - neg_imp[87]

tensor([ 0.0378, -0.0013, -0.0016, -0.0019, -0.0019, -0.0012, -0.0012, -0.0025,
        -0.0013, -0.0019, -0.0018, -0.0011, -0.0021, -0.0026, -0.0020, -0.0016,
        -0.0026, -0.0022, -0.0022, -0.0025, -0.0024])

In [81]:
self.feat_idx

tensor(87)

In [80]:
pos_imp[self.feat_idx] - neg_imp[self.feat_idx]

tensor([-0.0054, -0.0063, -0.0075, -0.0077, -0.0047, -0.0047, -0.0100, -0.0051,
        -0.0076, -0.0073, -0.0042, -0.0083, -0.0101, -0.0079, -0.0062, -0.0104,
        -0.0089, -0.0087, -0.0101, -0.0094])

In [37]:
ibin = 0
where = X == ibin

In [62]:
(X[:,45] == -1).sum()

tensor(70586)

In [22]:
for i , learner in enumerate(self.model.weak_learners):  # 使用 tqdm 显示进度条
    y_pred = learner.fit(x , y , w).predict(x)
    w = self.model.update_weight(w , y , y_pred)
    if i % 1 == 0: 
        txt = f'Round: {i+1}, Est-Err: {learner.min_feat_loss:.4f}'
        if feature is None: 
            txt += f', F_idx: {learner.feat_idx}'
        else:
            txt += f', F_name: {feature[learner.feat_idx]}'
        print(txt)

Round: 1, Est-Err: nan, F_name: FreeFloatCap_Ln
Round: 2, Est-Err: nan, F_name: FreeFloatCap_Ln


KeyboardInterrupt: 

In [3]:
model2.fit()

Lgbm

In [2]:
from src.api import DataAPI , Predictor

DataAPI.update()
DataAPI.prepare_predict_data()
Predictor.update_factors()

Update Files
Fri Aug 23 01:09:37 2024 : Updated ~ DB_information\calendar.feather Done! Cost 0.02 Secs
Fri Aug 23 01:09:37 2024 : Updated ~ DB_information\description.feather Done! Cost 0.04 Secs
Fri Aug 23 01:09:37 2024 : Updated ~ DB_information\st.feather Done! Cost 0.02 Secs
Fri Aug 23 01:09:40 2024 : Updated ~ DB_information\industry.feather Done! Cost 2.56 Secs
Fri Aug 23 01:09:45 2024 : Updated ~ DB_information\concepts.feather Done! Cost 5.18 Secs
Fri Aug 23 01:09:46 2024 : Updated ~ DB_models\longcl_exp\2024\longcl_exp.20240821.feather Done! Cost 0.11 Secs
Fri Aug 23 01:09:46 2024 : Updated ~ DB_models\risk_exp\2024\risk_exp.20240822.feather Done! Cost 0.06 Secs
Fri Aug 23 01:09:46 2024 : Updated ~ DB_models\risk_cov\2024\risk_cov.20240822.feather Done! Cost 0.03 Secs
Fri Aug 23 01:09:46 2024 : Updated ~ DB_models\risk_spec\2024\risk_spec.20240822.feather Done! Cost 0.02 Secs
Fri Aug 23 01:09:48 2024 : Updated ~ DB_trade\day\2024\day.20240822.feather Done! Cost 0.05 Secs
Fri A

KeyError: 'avg'

In [8]:
from src.data.tushare.download.info import Calendar , pro
renamer = {'cal_date' : 'calendar' ,'is_open'  : 'trade'}
fields = None
df = pro.trade_cal(exchange='SSE').rename(columns=renamer)
#df = df.sort_values('calendar').reset_index(drop = True)
df

Empty DataFrame
Columns: []
Index: []

In [10]:
# DataAPI.prepare_predict_data()
Predictor.update_factors()

Finish model [gru_day] predicting!
Finish model [gruRTN_day] predicting!
Finish model [gru_avg] predicting!
--------------------------------------------------------------------------------


In [1]:
from src.api import DataAPI , Predictor
# DataAPI.prepare_predict_data()
Predictor.update_factors()

d:\Coding\learndl\learndl\data\HistNorm\X_day.pt
Finish model [gru_day] predicting!
d:\Coding\learndl\learndl\data\HistNorm\X_day.pt
Finish model [gruRTN_day] predicting!
d:\Coding\learndl\learndl\data\HistNorm\X_day.pt
Finish model [gru_avg] predicting!
--------------------------------------------------------------------------------


In [ ]:
from src.api import ModelTestor
ModelTestor.new('ts_mixer').try_metrics()

Load  2 DataBlocks ...

... cost 0.22 secs
Align 2 DataBlocks ...... cost 0.21 secs
Pre-Norming method of [day] : {'divlast': True, 'histnorm': True}
x shape is torch.Size([5064, 30, 6])
y shape is torch.Size([5064, 1])
Test Forward Success
metrics :  Metrics.MetricOutput(loss=tensor(1.0688, grad_fn=<AddBackward0>), score=-0.015420470386743546, loss_item=1.068833589553833, penalty=0.0, losses=tensor(1.0688, grad_fn=<ExpBackward0>))
Test Metrics Success
