In [1]:
from src.model.boost import GeneralBooster

In [2]:
inputs = GeneralBooster.df_input()
inputs

{'train':                  Amount_20D_Avg  Amount_240D_Avg  Asset_LR  Asset_LR_Gr  \
 date     secid                                                            
 20211029 1             0.875544         0.875703  0.375270     0.775000   
          2             0.993958         0.994373  0.994009     0.516299   
          4             0.755437         0.861125  0.301701     0.438971   
          5             0.181489         0.158951  0.389648     0.067157   
          6             0.166022         0.183120  0.246585     0.946078   
 ...                         ...              ...       ...          ...   
 20230831 871970        0.010362         0.010567  0.030890     0.458824   
          871981        0.028687         0.030800  0.077007     0.230937   
          872925        0.029014         0.025629  0.018490     0.662309   
          873169        0.025742         0.055755  0.021101     0.489107   
          873223        0.029668         0.074978  0.037198     0.037473   
 
 

In [3]:
model1 = GeneralBooster('lgbm',**inputs).fit()
model2 = GeneralBooster('ada',**inputs).fit()

Round: 1, Est-Err: 0.4939, F_name: OCFA_Resd
Round: 2, Est-Err: 0.4960, F_name: Amount_20D_Avg
Round: 3, Est-Err: 0.4986, F_name: CL
Round: 4, Est-Err: 0.4992, F_name: OCFA_Para
Round: 5, Est-Err: 0.4992, F_name: BuyMinusSell_5D_Vol
Round: 6, Est-Err: 0.4985, F_name: Rating_R3M
Round: 7, Est-Err: 0.4995, F_name: Equity_LR_Gr
Round: 8, Est-Err: 0.4996, F_name: Num_Emp
Round: 9, Est-Err: 0.4997, F_name: BuyMinusSell_5D_Amount
Round: 10, Est-Err: 0.4990, F_name: OCFA_Resd
Round: 11, Est-Err: 0.4997, F_name: EPS_FY0_R1M
Round: 12, Est-Err: 0.4998, F_name: CloseTrend_240D_Reg
Round: 13, Est-Err: 0.4998, F_name: BuyMinusSell_5D_Vol
Round: 14, Est-Err: 0.4997, F_name: Bias_5D
Round: 15, Est-Err: 0.4998, F_name: ILLIQ_240D
Round: 16, Est-Err: 0.4998, F_name: NetProfitDeducted_SQ_YoY
Round: 17, Est-Err: 0.4998, F_name: MarketCap
Round: 18, Est-Err: 0.4998, F_name: BuyMinusSell_5D_Amount
Round: 19, Est-Err: 0.4997, F_name: FloatCap
Round: 20, Est-Err: 0.4998, F_name: IVR_20D
Round: 21, Est-Err: 

In [1]:
from src.api import DataAPI , Predictor

DataAPI.update()
DataAPI.prepare_predict_data()
Predictor.update_factors()

Update Files
Sun Aug 25 20:21:13 2024 : Updated ~ DB_information\calendar.feather Done! Cost 0.02 Secs
Sun Aug 25 20:21:13 2024 : Updated ~ DB_information\description.feather Done! Cost 0.03 Secs
Sun Aug 25 20:21:13 2024 : Updated ~ DB_information\st.feather Done! Cost 0.02 Secs
Sun Aug 25 20:21:15 2024 : Updated ~ DB_information\industry.feather Done! Cost 2.34 Secs
Sun Aug 25 20:21:20 2024 : Updated ~ DB_information\concepts.feather Done! Cost 5.19 Secs
Sun Aug 25 20:21:22 2024 : Updated ~ DB_models\longcl_exp\2024\longcl_exp.20240822.feather Done! Cost 0.10 Secs
Sun Aug 25 20:21:22 2024 : Updated ~ DB_models\risk_exp\2024\risk_exp.20240823.feather Done! Cost 0.05 Secs
Sun Aug 25 20:21:22 2024 : Updated ~ DB_models\risk_cov\2024\risk_cov.20240823.feather Done! Cost 0.03 Secs
Sun Aug 25 20:21:22 2024 : Updated ~ DB_models\risk_spec\2024\risk_spec.20240823.feather Done! Cost 0.02 Secs
Sun Aug 25 20:21:24 2024 : Updated ~ DB_trade\day\2024\day.20240823.feather Done! Cost 0.07 Secs
Sun A

FileNotFoundError: [Errno 2] No such file or directory: 'd:\\Coding\\learndl\\learndl\\models\\gru_day\\default.yaml'

In [8]:
from src.data.tushare.download.info import Calendar , pro
renamer = {'cal_date' : 'calendar' ,'is_open'  : 'trade'}
fields = None
df = pro.trade_cal(exchange='SSE').rename(columns=renamer)
#df = df.sort_values('calendar').reset_index(drop = True)
df

Empty DataFrame
Columns: []
Index: []

In [10]:
# DataAPI.prepare_predict_data()
Predictor.update_factors()

Finish model [gru_day] predicting!
Finish model [gruRTN_day] predicting!
Finish model [gru_avg] predicting!
--------------------------------------------------------------------------------


In [2]:
from src.api import DataAPI , Predictor
# DataAPI.prepare_predict_data()
md = Predictor.update_factors()

tensor([[ 10.2262],
        [  6.4458],
        [ -4.2535],
        ...,
        [  7.8719],
        [ -9.5733],
        [-43.3097]]) tensor([[  4.4866],
        [  5.0432],
        [ -8.9115],
        ...,
        [-27.7883],
        [-24.3357],
        [-64.8601]])
tensor([[  9.5268],
        [-13.1543],
        [  8.1235],
        ...,
        [  4.0610],
        [  2.5557],
        [-28.6509]]) tensor([[ 16.0309],
        [-25.3810],
        [  7.7358],
        ...,
        [ -1.2328],
        [-21.6224],
        [  3.7929]])
tensor([[  7.2132],
        [  8.2960],
        [-10.7186],
        ...,
        [  7.3211],
        [  2.0884],
        [-12.6653]]) tensor([[ -2.1297],
        [  2.6120],
        [-25.0220],
        ...,
        [  2.3501],
        [ -6.2634],
        [ -0.4066]])
tensor([[  6.7036],
        [  2.0849],
        [ -8.1760],
        ...,
        [  7.9754],
        [ -1.5401],
        [-12.5849]]) tensor([[-28.0546],
        [  2.8744],
        [ -6.0319],
  

In [3]:
app.net_0

AttributeError: 'NoneType' object has no attribute 'net_0'

In [ ]:
from 

pred0 = BatchOutput(net(batch_data.x)).pred
pred1 = net2(batch_data.x)

app.net_0 = net
app.net_1 = net2

self.net_x = batch_data

In [ ]:
from src.api import ModelTestor
ModelTestor.new('ts_mixer').try_metrics()

Load  2 DataBlocks ...

... cost 0.22 secs
Align 2 DataBlocks ...... cost 0.21 secs
Pre-Norming method of [day] : {'divlast': True, 'histnorm': True}
x shape is torch.Size([5064, 30, 6])
y shape is torch.Size([5064, 1])
Test Forward Success
metrics :  Metrics.MetricOutput(loss=tensor(1.0688, grad_fn=<AddBackward0>), score=-0.015420470386743546, loss_item=1.068833589553833, penalty=0.0, losses=tensor(1.0688, grad_fn=<ExpBackward0>))
Test Metrics Success
