In [48]:
import torch
n , m = 5000,3000
x  = torch.rand(n , m,2 ,6)
seq_len = 30
bs = 2000
i0 = torch.arange(bs)
i1 = torch.arange(m-bs,m)


In [52]:
x.unfold(1 , seq_len , 1)[i0 , i1 + 1 - seq_len].permute(0,3,1,2).shape

torch.Size([2000, 30, 2, 6])

In [46]:
%timeit a = torch.stack([x[i0,i1+i+1-seq_len] for i in range(seq_len)],dim=1).squeeze(2)

2.66 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [47]:
%timeit b = x.squeeze(2).unfold(1 , seq_len , 1)[i0 , i1 + 1 - seq_len].permute(0,2,1)

64.3 µs ± 6.12 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [42]:
a = torch.stack([x[i0,i1+i+1-seq_len] for i in range(seq_len)],dim=1).squeeze(2)
b = x.squeeze(2).unfold(1 , seq_len , 1)[i0 , i1 + 1 - seq_len].permute(0,2,1)

In [30]:
a.shape , b.shape

(torch.Size([10, 10, 6]), torch.Size([10, 10, 6]))

In [40]:
a[0] , b[0]

(tensor([[0.3420, 0.4648, 0.2487, 0.2869, 0.1787, 0.1203],
         [0.8335, 0.2715, 0.7964, 0.5515, 0.5741, 0.7030],
         [0.2232, 0.3538, 0.4778, 0.0379, 0.4688, 0.0576],
         [0.4691, 0.4410, 0.4744, 0.0314, 0.9227, 0.0948],
         [0.1755, 0.7252, 0.0445, 0.7557, 0.8255, 0.1719],
         [0.4937, 0.6015, 0.6012, 0.2059, 0.5123, 0.4419],
         [0.8865, 0.0562, 0.1788, 0.8029, 0.0188, 0.8559],
         [0.9209, 0.6778, 0.1168, 0.6957, 0.1292, 0.7379],
         [0.7027, 0.9662, 0.0025, 0.6155, 0.0023, 0.6209],
         [0.8938, 0.2262, 0.7920, 0.1817, 0.5340, 0.3241]]),
 tensor([[0.3420, 0.4648, 0.2487, 0.2869, 0.1787, 0.1203],
         [0.8335, 0.2715, 0.7964, 0.5515, 0.5741, 0.7030],
         [0.2232, 0.3538, 0.4778, 0.0379, 0.4688, 0.0576],
         [0.4691, 0.4410, 0.4744, 0.0314, 0.9227, 0.0948],
         [0.1755, 0.7252, 0.0445, 0.7557, 0.8255, 0.1719],
         [0.4937, 0.6015, 0.6012, 0.2059, 0.5123, 0.4419],
         [0.8865, 0.0562, 0.1788, 0.8029, 0.0188, 0.85

In [1]:
from run_model import RunModel
random_module = RunModel.random_module(module = 'patch_tst' , model_data_type = 'day' , model_data = None)

Load  2 DataBlocks ...... cost 0.08 secs
Align 2 DataBlocks ...... cost 0.13 secs
Pre-Norming method of [day] : [endpoint_division(True) , history_standardize(False)]


In [2]:
random_module.try_forward()

x shape is torch.Size([4980, 30, 6])
torch.Size([4980, 30, 6])
torch.Size([4980, 30, 6])
torch.Size([4980, 13, 6, 5])
torch.Size([4980, 32, 6])
torch.Size([4980, 32, 6])
torch.Size([4980, 192])
torch.Size([4980, 1])
y shape is torch.Size([4980, 1])


tensor([[0.4072],
        [0.4571],
        [0.3407],
        ...,
        [0.5042],
        [0.1480],
        [0.4499]], grad_fn=<AddmmBackward0>)