In [1]:
%run run_model.py --process=3 --rawname=1 --resume=1 --anchoring=1

24-02-08 06:55:39|MOD:run_model   |: Model Specifics:
24-02-08 06:55:39|MOD:run_model   |: Start Process [Load Data]!


--Process Queue : Data + Instance
--Confirm Resume Training!
--Model_name is set to TRA_LSTM_day!
{'verbosity': 2,
 'storage_type': 'mem',
 'device': device(type='cuda', index=0),
 'precision': 'float',
 'batch_size': 10000,
 'model_name': 'TRA_LSTM_day',
 'model_module': 'TRA_LSTM',
 'model_data_type': 'day',
 'model_num': 1,
 'beg_date': 20170103,
 'end_date': 99991231,
 'interval': 120,
 'input_step_day': 5,
 'test_step_day': 1,
 'MODEL_PARAM': {'hidden_dim': [64],
                 'seqlens': [{'day': 40, '15m': 20, 'dms': 40}],
                 'tra_seqlens': [{'hist_loss': 40}],
                 'rnn_layers': [2],
                 'mlp_layers': [1],
                 'dropout': [0.1],
                 'fc_in': [True],
                 'fc_att': [False],
                 'type_rnn': ['lstm'],
                 'rnn_att': [False],
                 'num_output': [1],
                 'kernel_size': [3, 3],
                 'hidden_as_factor': [False],
                 'ordered_param_gr

24-02-08 06:55:43|MOD:run_model   |: Finish Process [Load Data]! Cost 3.2Secs
24-02-08 06:55:43|MOD:run_model   |: Start Process [Copy to Instance]!
24-02-08 06:55:43|MOD:run_model   |: Copy from model to instance finished , Start going forward


Pre-Norming method of [day] : [endpoint_division(True) , history_standardize(True)]
score function of [pearson] calculated and success!


20170103     0.1458  0.1442  0.1438
20170704     0.1285  0.1275  0.1259
20171226     0.1450  0.1483  0.1458
20180627     0.1281  0.1280  0.1259
20181220     0.0968  0.0947  0.0962
20190624     0.0945  0.0961 -0.0072
20191217     0.0889  0.0884  0.0874
20200617     0.0747  0.0755  0.0754
20201214     0.0979  0.0989  0.0980
20210615     0.0462  0.0471  0.0477
20211209     0.0965  0.0943  0.0963
20220613     0.0803  0.0825  0.0199
20221206     0.0569  0.0598  0.0591
20230606     0.0640  0.0675  0.0693
20231201     0.0949  0.0932  0.0935
AllTimeAvg   0.0960  0.0966  0.0847
AllTimeSum   163.55  164.59  144.28
Std          0.0772  0.0757  0.0816
TValue        51.33   52.67   42.83
AnnIR        6.0915  6.2503  5.0828
24-02-08 06:59:16|MOD:run_model   |: Finish Process [Copy to Instance]! Cost 213.0 Secs


In [1]:
from run_model import * 

def new_random_input(module = 'tra_lstm2' , model_data_type = 'day' , model_data = None):

    config = train_config(override_config = {'model_module' : module , 'model_data_type' : model_data_type} , do_process=False)
    data_type_list = config.data_type_list
    for smp in config.model_params: smp.update(model_params_filler(data_type_list = data_type_list))
    model_data = ModelData(data_type_list , config)
    model_data.create_dataloader(*model_data.get_dataloader_param('train','train',20170104,config.model_params[0]))
    
    #inday_dim_dict = {'15m' : 16 , '30m' : 8 , '60m' : 4 , '120m' : 2}
    for i , batch_data in enumerate(model_data.dataloaders['train']):
        batch_data = batch_data
        break
    net = new_net(module , param = config.model_params[0])
    return net , batch_data , model_data

net , batch_data , model_data = new_random_input()

usage: ipykernel_launcher.py [-h] [--process PROCESS] [--rawname RAWNAME]
                             [--resume RESUME] [--anchoring ANCHORING]
ipykernel_launcher.py: error: unrecognized arguments: --f=c:\Users\jinmeng\AppData\Roaming\jupyter\runtime\kernel-v2-16620Iv4LGbZ7ymXs.json


use d:\Coding\learndl\learndl\scripts\util/../../data/torch_pack/day+rtn11+res11.20231222.pt
Pre-Norming method of [day] : [endpoint_division(True) , history_standardize(True)]


In [2]:
net.dynamic_data_assign(batch_data , model_data)
net(batch_data['x']) , batch_data['y']

((tensor([[0.0867],
          [0.0472],
          [0.0484],
          ...,
          [0.0460],
          [0.0476],
          [0.0547]], grad_fn=<SumBackward1>),
  tensor([[-0.1038,  0.1009, -0.0315,  ...,  0.0290,  0.0731,  0.1308],
          [-0.0927,  0.0907, -0.0234,  ...,  0.0006,  0.1136,  0.1002],
          [-0.1030,  0.0872, -0.0305,  ...,  0.0111,  0.0954,  0.1172],
          ...,
          [-0.0609,  0.0836, -0.0369,  ...,  0.0289,  0.1214,  0.1175],
          [-0.0798,  0.0881, -0.0388,  ...,  0.0179,  0.0939,  0.1199],
          [-0.1133,  0.0842, -0.0278,  ...,  0.0129,  0.0782,  0.1264]],
         grad_fn=<AddmmBackward0>)),
 tensor([[ 0.3875],
         [ 0.4519],
         [-0.7027],
         ...,
         [ 1.1804],
         [-1.3341],
         [-0.1899]]))

In [3]:
class test:
    def __init__(self , n) -> None:
        self.a = n

In [4]:
a = test(3)
b = test(4)
a.a , b.a

(3, 4)

In [6]:
a.b = b
a.a = a.b.a
a.a , b.a

(4, 4)

In [7]:
a.b.a = 5
a.a , b.a

(4, 5)

In [4]:
a = net.get_probs()

In [5]:
a

[tensor([[0.2050, 0.1918, 0.2121, 0.1930, 0.1981]])]

In [17]:
a = None
torch.concat([torch.rand(2,3,4), a] if a is not None else [torch.rand(2,3,4)])

tensor([[[0.8426, 0.3418, 0.4790, 0.4916],
         [0.7773, 0.6809, 0.3131, 0.3789],
         [0.0613, 0.5946, 0.9516, 0.7583]],

        [[0.6826, 0.1543, 0.4325, 0.3777],
         [0.9519, 0.4940, 0.3675, 0.8293],
         [0.6968, 0.6019, 0.7147, 0.7691]]])

In [26]:
x.shape , hist_loss.shape

NameError: name 'hist_loss' is not defined

In [11]:
import torch
import torch.nn as nn

class tra_module:
    '''
    Decorator to grant a module dynamic data access, and output probs (tra feature)
    '''
    def __call__(self, original_class):
        class new_tra_class(original_class):
            def __init__(self , *args , **kwargs):
                super().__init__(*args , **kwargs)
                self.dynamic_data_assigned = False
            def __call__(self , *args , **kwargs):
                assert self.dynamic_data_assigned , f'Run dynamic_data_assign first'
                self.dynamic_data_assigned = False
                return super().__call__(*args , **kwargs)
            def dynamic_data_assign(self , batch_data , model_data , **kwargs):
                self.dynamic_data = {'model_data':model_data,'batch_data':batch_data,**kwargs}
                self.dynamic_data_assigned = True
            def get_probs(self):
                v = torch.rand(2,5)
                return v/v.sum(dim=1,keepdim=True)   
                if self.probs_record is not None: return self.probs_record/self.probs_record.sum(dim=1,keepdim=True)   
        return new_tra_class

class tra_component:
    '''
    Decorator to identify a component of a module as tra components, apply pipeline dynamic data access, and output probs (tra feature)
    '''
    def __init__(self, *args):
        self.tra_component_list = args
    def __call__(self, original_class):
        tra_component_list = self.tra_component_list
        class new_tra_class(original_class):
            def dynamic_data_assign(self , *args , **kwargs):
                for comp in tra_component_list:
                    getattr(self , comp).dynamic_data_assign(*args , **kwargs)
            def dynamic_data_access(self , *args , **kwargs):
                dynamic_data = [getattr(self , comp).dynamic_data for comp in tra_component_list]
                return dynamic_data if len(dynamic_data) > 1 else dynamic_data[0]
            def get_probs(self , *args , **kwargs):
                probs = [getattr(self,comp).get_probs(*args , **kwargs) for comp in tra_component_list]
                return probs if len(probs) > 1 else probs[0]
        return new_tra_class

@tra_module()
class mod_tra(nn.Module):
    def __init__(self , input_dim , output_dim , dropout=0.0 , num_layers = 2):
        super().__init__()
        num_layers = min(3,num_layers)
        self.lstm = nn.LSTM(input_dim , output_dim , num_layers = num_layers , dropout = dropout , batch_first = True)
    def forward(self, inputs):
        return self.lstm(inputs)[0]

@tra_component('tra1' , 'tra2')
class mod_tra2(nn.Module):
    def __init__(self , input_dim , output_dim , dropout=0.0 , num_layers = 2):
        super().__init__()
        self.tra1 = mod_tra(input_dim , output_dim)
        self.tra2 = mod_tra(input_dim , output_dim)
    def forward(self, inputs):
        return self.tra1(inputs) + self.tra2(inputs)

obj = mod_tra2(6,4)

In [29]:
a = torch.ones(10).fill_(torch.nan)
a.mean()

tensor(nan)

In [12]:
obj.dynamic_data_assign(batch_data = 1,model_data = 2)
obj.tra1.dynamic_data_assigned , obj.tra2.dynamic_data_assigned

(True, True)

In [13]:
obj = mod_tra2(6,4)
obj.dynamic_data_assign(batch_data = 1,model_data = 2)
obj(torch.rand(2,10,6))
obj.get_probs()

[tensor([[0.2405, 0.2494, 0.2031, 0.1997, 0.1073],
         [0.4132, 0.1782, 0.1846, 0.1987, 0.0254]]),
 tensor([[0.1323, 0.2215, 0.2372, 0.2747, 0.1342],
         [0.2788, 0.2884, 0.1591, 0.2695, 0.0042]])]

In [14]:
obj.dynamic_data_access()

[{'model_data': 2, 'batch_data': 1}, {'model_data': 2, 'batch_data': 1}]