In [1]:
%run run_model.py --process=3 --rawname=1 --resume=1 --anchoring=1

24-02-08 06:55:39|MOD:run_model   |: Model Specifics:
24-02-08 06:55:39|MOD:run_model   |: Start Process [Load Data]!


--Process Queue : Data + Instance
--Confirm Resume Training!
--Model_name is set to TRA_LSTM_day!
{'verbosity': 2,
 'storage_type': 'mem',
 'device': device(type='cuda', index=0),
 'precision': 'float',
 'batch_size': 10000,
 'model_name': 'TRA_LSTM_day',
 'model_module': 'TRA_LSTM',
 'model_data_type': 'day',
 'model_num': 1,
 'beg_date': 20170103,
 'end_date': 99991231,
 'interval': 120,
 'input_step_day': 5,
 'test_step_day': 1,
 'MODEL_PARAM': {'hidden_dim': [64],
                 'seqlens': [{'day': 40, '15m': 20, 'dms': 40}],
                 'tra_seqlens': [{'hist_loss': 40}],
                 'rnn_layers': [2],
                 'mlp_layers': [1],
                 'dropout': [0.1],
                 'fc_in': [True],
                 'fc_att': [False],
                 'type_rnn': ['lstm'],
                 'rnn_att': [False],
                 'num_output': [1],
                 'kernel_size': [3, 3],
                 'hidden_as_factor': [False],
                 'ordered_param_gr

24-02-08 06:55:43|MOD:run_model   |: Finish Process [Load Data]! Cost 3.2Secs
24-02-08 06:55:43|MOD:run_model   |: Start Process [Copy to Instance]!
24-02-08 06:55:43|MOD:run_model   |: Copy from model to instance finished , Start going forward


Pre-Norming method of [day] : [endpoint_division(True) , history_standardize(True)]
score function of [pearson] calculated and success!


20170103     0.1458  0.1442  0.1438
20170704     0.1285  0.1275  0.1259
20171226     0.1450  0.1483  0.1458
20180627     0.1281  0.1280  0.1259
20181220     0.0968  0.0947  0.0962
20190624     0.0945  0.0961 -0.0072
20191217     0.0889  0.0884  0.0874
20200617     0.0747  0.0755  0.0754
20201214     0.0979  0.0989  0.0980
20210615     0.0462  0.0471  0.0477
20211209     0.0965  0.0943  0.0963
20220613     0.0803  0.0825  0.0199
20221206     0.0569  0.0598  0.0591
20230606     0.0640  0.0675  0.0693
20231201     0.0949  0.0932  0.0935
AllTimeAvg   0.0960  0.0966  0.0847
AllTimeSum   163.55  164.59  144.28
Std          0.0772  0.0757  0.0816
TValue        51.33   52.67   42.83
AnnIR        6.0915  6.2503  5.0828
24-02-08 06:59:16|MOD:run_model   |: Finish Process [Copy to Instance]! Cost 213.0 Secs


In [7]:
from run_model import * 

net , x , y = new_random_input('ResNet_LSTM' , '30m')
net(x) , y

((tensor([[ 0.8244],
          [-0.8244]], grad_fn=<CatBackward0>),
  tensor([[ 0.0150, -0.0151,  0.0328,  0.0110, -0.0407, -0.0875, -0.0561, -0.0384,
           -0.0614,  0.0018, -0.0611, -0.1183,  0.0858, -0.1193, -0.1083, -0.1048,
            0.0545,  0.0358, -0.1490,  0.0227,  0.1039,  0.1015, -0.1277, -0.0368,
            0.0947, -0.0881,  0.0536,  0.0759, -0.0913, -0.0826,  0.0479, -0.0714,
            0.0476,  0.1189, -0.0798,  0.0711,  0.0692, -0.0146, -0.1710, -0.0201,
            0.0053, -0.0978, -0.1515, -0.0618,  0.0748,  0.1126, -0.0168, -0.0885,
           -0.0999, -0.1310,  0.0005, -0.0547, -0.0484, -0.0192,  0.0115,  0.0833,
           -0.1187, -0.1257,  0.1197, -0.0753,  0.0007, -0.0495, -0.1086,  0.1079],
          [ 0.0530, -0.0267,  0.0408, -0.0038, -0.0435, -0.0722, -0.0830, -0.0138,
           -0.0461, -0.0029, -0.0767, -0.1159,  0.0926, -0.1050, -0.1398, -0.0993,
            0.0514,  0.0300, -0.1183,  0.0063,  0.1082,  0.1206, -0.1221, -0.0250,
            0.0894

In [20]:
net(x)

(tensor([[ 0.8050],
         [-0.8050]], grad_fn=<CatBackward0>),
 tensor([[-0.0043,  0.0230, -0.0724, -0.0051, -0.0170, -0.0417,  0.1198,  0.0162,
           0.0065,  0.0669, -0.0142,  0.0682,  0.0672,  0.0975, -0.1097,  0.0147,
          -0.0106, -0.0431,  0.1217, -0.0439,  0.0584,  0.1293,  0.0923,  0.0027,
           0.0279,  0.0484,  0.0966, -0.0188, -0.0034, -0.0446,  0.1307,  0.0209,
          -0.0230, -0.0275,  0.0201, -0.0880, -0.1329,  0.1055, -0.0347, -0.1129,
          -0.0720, -0.0871,  0.0238,  0.0540,  0.0128, -0.0959,  0.0696, -0.1054,
           0.0717, -0.0020,  0.0773,  0.0373, -0.0932,  0.1856,  0.1003,  0.0376,
           0.1033, -0.1120,  0.0046, -0.1180, -0.0295,  0.0177,  0.0780, -0.0852],
         [ 0.0038,  0.0252, -0.0847,  0.0183, -0.0090, -0.0060,  0.0791,  0.0243,
          -0.0389,  0.0877,  0.0175,  0.0573,  0.1012,  0.0882, -0.1257,  0.0270,
          -0.0339, -0.0702,  0.1098, -0.0691,  0.0365,  0.0791,  0.0758,  0.0029,
           0.0114,  0.0738,  0.

In [3]:
x['30m'].shape , y.shape

(torch.Size([2, 30, 8, 6]), torch.Size([2, 1]))

In [4]:
net = new_net(config.model_module , model_params[0])
o , h = net(x['30m'])

In [5]:
h.shape

torch.Size([2, 64])

In [23]:
x1 = net.encoder.mod_list[0].fc_enc_in(x)
net.encoder.mod_list[0].fc_rnn(x1).shape

torch.Size([2, 30, 64])

In [24]:
net.encoder.mod_list[0]

uni_rnn_encoder(
  (fc_enc_in): resnet_1d(
    (blocks): Sequential(
      (0): resnet_block_1d(
        (downsample): Conv1d(6, 16, kernel_size=(1,), stride=(1,))
        (conv): Sequential(
          (0): Conv1d(6, 4, kernel_size=(1,), stride=(1,))
          (1): BatchNorm1d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
          (3): Conv1d(4, 4, kernel_size=(3,), stride=(1,), padding=(1,), bias=False)
          (4): BatchNorm1d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): ReLU()
          (6): Conv1d(4, 16, kernel_size=(1,), stride=(1,))
          (7): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (8): ReLU()
        )
      )
      (1): resnet_block_1d(
        (downsample): Sequential()
        (conv): Sequential(
          (0): Conv1d(16, 4, kernel_size=(1,), stride=(1,))
          (1): BatchNorm1d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stat

In [14]:
a = {'a' : None}
a.get('a' )

In [6]:
if None and 'a' == 'a':
    print(1)

In [6]:

import torch
import torch.nn as nn
# pip install pytimedinput -i https://pypi.tuna.tsinghua.edu.cn/simple
from scripts.nn.My import mod_gru
from scripts.nn.ResNet import resnet_1d, resnet_2d
    
class resnet1d_gru(nn.Module):
    def __init__(self, seq_len , feat_len , dim_res = 16 , dim_rnn = 64 , *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.resnet = resnet_1d(seq_len , feat_len , dim_res , 10 , 3) 
        self.gru    = mod_gru(dim_res , dim_rnn , 0.1 , 2)
    def forward(self , x):
        hidden = self.resnet(x)
        print("hidden shape :" , hidden.shape)
        output = self.gru(hidden)[:,-1,:]
        print("output shape :" , output.shape)
        return output
    
class resnet2d_gru(nn.Module):
    def __init__(self, seq_len , feat_len , dim_res = 16 , dim_rnn = 64 , *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.resnet = resnet_2d(seq_len , feat_len , dim_res , 10 , 3) 
        self.gru    = mod_gru(dim_res , dim_rnn , 0.1 , 2)
    def forward(self , x):
        hidden = self.resnet(x)
        output = self.gru(hidden)[:,-1,:]
        print("hidden shape :" , hidden.shape)
        print("output shape :" , output.shape)
        return output
    

batch_n  = 2
seq_day  = 30
seq_inday  = 8
feat_len = 5
dim_out  = 64
x = torch.randn(batch_n,seq_day,seq_inday,feat_len)

net_1d = resnet1d_gru(seq_inday , feat_len , dim_res = dim_out // 4 , dim_rnn = dim_out)
net_2d = resnet2d_gru(seq_inday , feat_len , dim_res = dim_out // 4 , dim_rnn = dim_out)
y1 = net_1d(x)
y2 = net_2d(x)


hidden shape : torch.Size([2, 30, 16])
output shape : torch.Size([2, 64])
hidden shape : torch.Size([2, 30, 16])
output shape : torch.Size([2, 64])
