In [1]:
%run run_model.py --process=3 --rawname=1 --resume=1 --anchoring=1

24-02-08 06:55:39|MOD:run_model   |: Model Specifics:
24-02-08 06:55:39|MOD:run_model   |: Start Process [Load Data]!


--Process Queue : Data + Instance
--Confirm Resume Training!
--Model_name is set to TRA_LSTM_day!
{'verbosity': 2,
 'storage_type': 'mem',
 'device': device(type='cuda', index=0),
 'precision': 'float',
 'batch_size': 10000,
 'model_name': 'TRA_LSTM_day',
 'model_module': 'TRA_LSTM',
 'model_data_type': 'day',
 'model_num': 1,
 'beg_date': 20170103,
 'end_date': 99991231,
 'interval': 120,
 'input_step_day': 5,
 'test_step_day': 1,
 'MODEL_PARAM': {'hidden_dim': [64],
                 'seqlens': [{'day': 40, '15m': 20, 'dms': 40}],
                 'tra_seqlens': [{'hist_loss': 40}],
                 'rnn_layers': [2],
                 'mlp_layers': [1],
                 'dropout': [0.1],
                 'fc_in': [True],
                 'fc_att': [False],
                 'type_rnn': ['lstm'],
                 'rnn_att': [False],
                 'num_output': [1],
                 'kernel_size': [3, 3],
                 'hidden_as_factor': [False],
                 'ordered_param_gr

24-02-08 06:55:43|MOD:run_model   |: Finish Process [Load Data]! Cost 3.2Secs
24-02-08 06:55:43|MOD:run_model   |: Start Process [Copy to Instance]!
24-02-08 06:55:43|MOD:run_model   |: Copy from model to instance finished , Start going forward


Pre-Norming method of [day] : [endpoint_division(True) , history_standardize(True)]
score function of [pearson] calculated and success!


20170103     0.1458  0.1442  0.1438
20170704     0.1285  0.1275  0.1259
20171226     0.1450  0.1483  0.1458
20180627     0.1281  0.1280  0.1259
20181220     0.0968  0.0947  0.0962
20190624     0.0945  0.0961 -0.0072
20191217     0.0889  0.0884  0.0874
20200617     0.0747  0.0755  0.0754
20201214     0.0979  0.0989  0.0980
20210615     0.0462  0.0471  0.0477
20211209     0.0965  0.0943  0.0963
20220613     0.0803  0.0825  0.0199
20221206     0.0569  0.0598  0.0591
20230606     0.0640  0.0675  0.0693
20231201     0.0949  0.0932  0.0935
AllTimeAvg   0.0960  0.0966  0.0847
AllTimeSum   163.55  164.59  144.28
Std          0.0772  0.0757  0.0816
TValue        51.33   52.67   42.83
AnnIR        6.0915  6.2503  5.0828
24-02-08 06:59:16|MOD:run_model   |: Finish Process [Copy to Instance]! Cost 213.0 Secs


In [4]:
from run_model import * 

"""
net , x , y = new_random_input('ResNet_LSTM' , '30m')
net(x) , y

net , x , y = new_random_input('TRA_LSTM' , 'day')
# x = torch.concat(x.unbind(1),1)
hist_loss = torch.rand((*x.shape[:-1],3))
net((x , hist_loss)) , y
"""
net , x , y = new_random_input('TRA_LSTM' , 'day')
# x = torch.concat(x.unbind(1),1)
hist_loss = torch.rand((*x.shape[:-1],3))
net((x , hist_loss)) , y

((tensor([[-0.0191],
          [-0.0260]], grad_fn=<SumBackward1>),
  tensor([[-0.1066, -0.0298, -0.0047],
          [-0.1008, -0.0258, -0.0168]], grad_fn=<AddmmBackward0>)),
 tensor([[0.8924],
         [0.6569]]))

In [7]:
net.probs , net.probs_record

(tensor([[0.0803, 0.2445, 0.6752],
         [0.0032, 0.9855, 0.0112]], grad_fn=<SoftmaxBackward0>),
 tensor([[0.0835, 1.2300, 0.6865]]))

In [26]:
x.shape , hist_loss.shape

NameError: name 'hist_loss' is not defined

In [21]:
net

MyTRA_LSTM(
  (base_model): Sequential(
    (0): mod_parallel(
      (mod_list): ModuleList(
        (0): uni_rnn_encoder(
          (fc_enc_in): Sequential()
          (fc_rnn): mod_lstm(
            (lstm): LSTM(16, 64, num_layers=2, batch_first=True, dropout=0.1)
          )
        )
      )
    )
    (1): mod_parallel(
      (mod_list): ModuleList(
        (0): uni_rnn_decoder(
          (fc_dec_mlp): Sequential(
            (0): Sequential(
              (0): Linear(in_features=64, out_features=64, bias=True)
              (1): LeakyReLU(negative_slope=0.01)
              (2): Dropout(p=0.1, inplace=False)
            )
          )
          (fc_hid_out): Linear(in_features=64, out_features=64, bias=True)
        )
      )
    )
  )
  (router): LSTM(3, 8, batch_first=True)
  (fc): Linear(in_features=72, out_features=3, bias=True)
  (predictors): Linear(in_features=64, out_features=3, bias=True)
)

In [2]:
x.shape

torch.Size([2, 30, 8, 6])

In [9]:
x1 = torch.concat(x.unbind(1),1)

TypeError: unbind() received an invalid combination of arguments - got (tuple), but expected one of:
 * (int dim)
      didn't match because some of the arguments have invalid types: (!tuple of (int, int)!)
 * (name dim)
      didn't match because some of the arguments have invalid types: (!tuple of (int, int)!)


In [4]:
x2 = x.reshape(2,-1,6)

In [8]:
x1.shape 

torch.Size([2, 240, 6])