In [1]:
from src.algo.nn.model import TFT

main path: /Users/mengkjin/workspace/learndl
src.INSTANCE_RECORD can be accessed to check ['trainer', 'account', 'factor']


In [1]:
from src.api import ModelAPI  
ModelAPI.Trainer.available_modules()

main path: /Users/mengkjin/workspace/learndl
src.INSTANCE_RECORD can be accessed to check ['trainer', 'account', 'factor']


{'simple_lstm': src.algo.nn.model.Recurrent.simple_lstm,
 'gru': src.algo.nn.model.Recurrent.gru,
 'lstm': src.algo.nn.model.Recurrent.lstm,
 'resnet_lstm': src.algo.nn.model.Recurrent.resnet_lstm,
 'resnet_gru': src.algo.nn.model.Recurrent.resnet_gru,
 'transformer': src.algo.nn.model.Recurrent.transformer,
 'tcn': src.algo.nn.model.Recurrent.tcn,
 'rnn_ntask': src.algo.nn.model.Recurrent.rnn_ntask,
 'rnn_general': src.algo.nn.model.Recurrent.rnn_general,
 'gru_dsize': src.algo.nn.model.Recurrent.gru_dsize,
 'patch_tst': src.algo.nn.model.PatchTST.patch_tst,
 'modern_tcn': src.algo.nn.model.ModernTCN.modern_tcn,
 'ts_mixer': src.algo.nn.model.TSMixer.ts_mixer,
 'tra': src.algo.nn.model.TRA.tra,
 'factor_vae': src.algo.nn.model.FactorVAE.FactorVAE,
 'risk_att_gru': src.algo.nn.model.RiskAttGRU.risk_att_gru,
 'ple_gru': src.algo.nn.model.PLE.ple_gru,
 'tft': src.algo.nn.model.TemporalFusionTransformer.TemporalFusionTransformer,
 'lgbm': src.algo.boost.booster.lgbm.Lgbm,
 'ada': src.algo

In [1]:
from src.api import ModelAPI  
from src.basic.util.logger import MessageCapturer

app = ModelAPI.short_test(module = 'tft')

main path: /Users/mengkjin/workspace/learndl
src.INSTANCE_RECORD can be accessed to check ['trainer', 'account', 'factor']
--------------------------------------------------------------------------------
***************************** PARSER TRAINING ARGS *****************************
--Process Queue : Data + Fit + Test
--Start Training New!
--Model_name is set to tft_day_ShortTest!
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
******************************* SETUP CALLBACKS *******************************
ResetOptimizer(num_reset=2,trigger=40,recover_level=1.0,speedup2x=True) , reset optimizer on some epoch (can speedup scheduler)
CallbackTimer(verbosity=10) , record time cost of callback hooks
EarlyStoppage(patience=20) , stop fitting when validation score cease to improve
ValidationConverge(patience=5,eps=1e-05) , stop fitting when valid_score converge
EarlyExitRetrain(

25-06-16 23:48:13|MOD:logger      |: Model Specifics:


--------------------------------------------------------------------------------
********************************** MODEL INFO **********************************
Model Name   : tft_day_ShortTest
Model Module : tft
  -->  Model Params :
    -->  hidden_dim : [16]
    -->  seqlens : [{'day': 30, 'indus': 30}]
    -->  dropout : [0.1]
    -->  ffn_dim : [32]
    -->  num_heads : [4]
    -->  pred_len : [1]
    -->  encoder_layers : [2]
    -->  model.submodels : ['best']
    -->  model.input_type : data
    -->  model.data.types : day+indus
    -->  verbosity : 10
Model Inputs : data
  -->  Data Types : ['day', 'indus']
Model Labels : ['std_lag1_10', 'rtn_lag1_10']
Model Period : 20240701 ~ 20240930
Sampling     : sequential
Shuffling    : epoch
Random Seed  : None
--------------------------------------------------------------------------------


25-06-16 23:48:13|MOD:logger      |: Start Process [Data] at Mon Jun 16 23:48:13 2025!


try using /Users/mengkjin/workspace/learndl/data/Interim/DataSet/day+indus.20241211.pt , success!
Pre-Norming method of [day] : {'divlast': True, 'histnorm': True}
Pre-Norming method of [indus] : {'divlast': False, 'histnorm': False}


25-06-16 23:48:16|MOD:logger      |: Finish Process [Data], Cost 2.4 Secs
25-06-16 23:48:16|MOD:logger      |: Start Process [Fit] at Mon Jun 16 23:48:16 2025!
25-06-16 23:48:16|MOD:logger      |: First Iterance: (20240701 , 0)
Train Ep#  0 loss : 0.00000:   0%|          | 0/38 [00:00<?, ?it/s]

score function of [spearman] calculated and success!
loss function of [net_specific] calculated and success!


Valid Ep#  0 score : -0.01147: 100%|██████████| 10/10 [00:03<00:00,  2.85it/s]
FirstBite Ep#  0 : loss  nan, train 0.01383, valid 0.01028, best 0.0103, lr1.3e-03
25-06-16 23:48:49|MOD:logger      |: Initialize a new model to retrain! Lives remaining 4


{'max_epoch': 1, 'stage': 'fit', 'dataset': 'valid', 'epoch': -1, 'attempt': 0, 'round': 0, 'model_num': 0, 'model_date': 20240701, 'model_submodel': 'best', 'epoch_event': [], 'best_attempt_metric': None, 'fitted_model_num': 0}


25-06-16 23:48:49|MOD:logger      |: Main Process Finished! Cost 35.9 Seconds
MessageCapturer Finished Capturing Train Model Of Short Test, saved to /Users/mengkjin/workspace/learndl/models/tft_day_ShortTest/detailed_analysis/training_output.html


KeyError: 'model_date'

In [9]:
from src.basic import INSTANCE_RECORD
trainer = INSTANCE_RECORD.trainer
trainer.model.batch_data.valid.sum() , trainer.model.batch_data.shape

(tensor(4993, device='mps:0'),
 {'x': (torch.Size([4993, 30, 6]), torch.Size([4993, 30, 35])),
  'y': torch.Size([4993, 1]),
  'w': None,
  'i': torch.Size([4993, 2]),
  'valid': torch.Size([4993])})

In [11]:
from src.model.util import BatchOutput
batch_output = BatchOutput.nn_module(trainer.model.net , trainer.model.batch_data)

In [13]:
batch_output['predictions']

tensor([[[ 0.3959, -0.0357,  0.7765]],

        [[-0.2095,  0.4502,  0.3229]],

        [[ 0.5385, -0.0360,  0.9484]],

        ...,

        [[ 0.0537,  0.4237,  0.7610]],

        [[-0.2501,  0.3930,  0.1985]],

        [[ 0.4268,  0.1428,  0.7888]]], device='mps:0')

In [18]:
trainer.model.net.loss(trainer.model.batch_data.y , **batch_output.items())

tensor([nan], device='mps:0')

In [24]:
batch_output.shape

{'pred': torch.Size([4993, 1]),
 'predictions': torch.Size([4993, 1, 3]),
 'static_weights': torch.Size([4993, 30, 8]),
 'historical_weights': torch.Size([4993, 30, 6]),
 'future_weights': float}

In [23]:
import torch

def loss(label : torch.Tensor , pred : torch.Tensor | None = None , w : torch.Tensor | None = None , dim = None , 
         quantiles : list[float] = [0.1,0.5,0.9] , predictions : torch.Tensor | None = None , **kwargs):
    assert predictions is not None , f'predictions should be provided'
    assert predictions.shape[-1] == len(quantiles) , f'shape of predictions {predictions.shape} should be (...,{len(quantiles)})'
    if predictions.ndim == label.ndim + 1: predictions = predictions[...,0]
    assert predictions.ndim == label.ndim == 2 , f'shape of predictions {predictions.shape} and label {label.shape} should be (...,1)'
    if w is None:
        w1 = 1.
    else:
        w1 = w / w.sum(dim=dim,keepdim=True) * (w.numel() if dim is None else w.size(dim=dim))
    
    losses = []
    label = label.expand_as(predictions)
    for i, q in enumerate(quantiles):
        pred_q = predictions[..., i:i+1]
        error = label - pred_q
        valid = ~error.isnan()
        loss = torch.max(q * error[valid], (q - 1) * error[valid])
        print(loss)
        losses.append((w1 * loss).mean(dim=dim,keepdim=True))
    print(losses)
    v = torch.stack(losses,dim=-1).mean(dim=-1)
    return v

loss(trainer.model.batch_data.y , **batch_output.items())

tensor(0, device='mps:0') torch.Size([4993, 1]) torch.Size([4993, 1])
tensor([0.2509, 0.7786, 1.0646,  ..., 0.0471, 0.0449, 0.6996], device='mps:0')
tensor([], device='mps:0')
tensor([], device='mps:0')
[tensor([0.4907], device='mps:0'), tensor([nan], device='mps:0'), tensor([nan], device='mps:0')]


tensor([nan], device='mps:0')

In [1]:
import torch
import gc


def test_operations(iterations: int, shape: tuple[int, int]) -> None:
    print(f"PyTorch version: {torch.__version__}")
    # Test 1: torch.unique
    print("\nTest 1: torch.unique")
    x = torch.randint(0, 2, shape, device="mps")
    for i in range(iterations):
        y = torch.unique(x)
        del y

        # Empty cache and collect garbage to make sure
        torch.mps.empty_cache()
        gc.collect()

        if i % 10 == 0:
            print(
                f"Iter {i}: Driver Allocated Memory: {torch.mps.driver_allocated_memory() / (1024**2):.2f}MB, Current Allocated Memory: {torch.mps.current_allocated_memory() / (1024**2):.2f}MB"
            )

    # Test 2: torch.sort (comparison)
    print("\nTest 2: torch.sort")
    for i in range(iterations):
        y = torch.sort(x)[0]
        del y
        # Empty cache and collect garbage to make sure
        torch.mps.empty_cache()
        gc.collect()

        if i % 10 == 0:
            print(
                f"Iter {i}: Driver memory: {torch.mps.driver_allocated_memory() / (1024**2):.2f}MB, Current memory: {torch.mps.current_allocated_memory() / (1024**2):.2f}MB"
            )


test_operations(iterations=100, shape=(2000, 10))

PyTorch version: 2.7.1

Test 1: torch.unique
Iter 0: Driver Allocated Memory: 10.73MB, Current Allocated Memory: 0.15MB
Iter 10: Driver Allocated Memory: 10.73MB, Current Allocated Memory: 0.15MB
Iter 20: Driver Allocated Memory: 10.73MB, Current Allocated Memory: 0.15MB
Iter 30: Driver Allocated Memory: 10.72MB, Current Allocated Memory: 0.15MB
Iter 40: Driver Allocated Memory: 10.72MB, Current Allocated Memory: 0.15MB
Iter 50: Driver Allocated Memory: 10.72MB, Current Allocated Memory: 0.15MB
Iter 60: Driver Allocated Memory: 10.72MB, Current Allocated Memory: 0.15MB
Iter 70: Driver Allocated Memory: 10.72MB, Current Allocated Memory: 0.15MB
Iter 80: Driver Allocated Memory: 10.72MB, Current Allocated Memory: 0.15MB
Iter 90: Driver Allocated Memory: 10.72MB, Current Allocated Memory: 0.15MB

Test 2: torch.sort
Iter 0: Driver memory: 10.72MB, Current memory: 0.15MB
Iter 10: Driver memory: 10.72MB, Current memory: 0.15MB
Iter 20: Driver memory: 10.72MB, Current memory: 0.15MB
Iter 30: 

In [2]:
from src.api import ModelAPI
ModelAPI.clear_st_models()

Deleting lgbm_day_ShortTest in /Users/mengkjin/workspace/learndl/models


In [3]:
from src import INSTANCE_RECORD
INSTANCE_RECORD

InstanceRecord(names=['trainer', 'account'])

In [1]:
from src.api import ModelAPI
ModelAPI.Extractor.update()



model_name is None, update all hidden models
{'name': 'gru_day', 'nums': None, 'submodels': ['best']}
Beware! Should be at server or short_test, but short_test is False now!
try using d:\Coding\learndl\learndl\data\DataSet/day.20240607.pt , success!
Load  2 DataBlocks...... finished! Cost 0.08 secs
Align 2 DataBlocks...... finished! Cost 0.21 secs
Pre-Norming method of [day] : {'divlast': True, 'histnorm': True}


100%|██████████| 316/316 [00:00<00:00, 3047.38it/s]

--------------------------------------------------------------------------------


In [1]:
from src.api import ModelAPI

ModelAPI.update_models()

src.basic.INSTANCE_RECORD can be accessed to check ['trainer', 'account']
Basic module imported!
Use device name: NVIDIA GeForce RTX 4090


24-12-15 18:40:32|MOD:display     |: Model Specifics:
24-12-15 18:40:32|MOD:display     |: Start Process [Data] at Sun Dec 15 18:40:32 2024!


--------------------------------------------------------------------------------
**************************** RECONSTRUCT TRAIN DATA ****************************
predict is False , Data Processing start!
6 datas : ['y', 'day', '30m', 'style', 'indus', 'week'] , from 20070101 to None
y is up to 20241215121914 already!
day is up to 20241215122636 already!
30m is up to 20241215122719 already!
style is up to 20241215124444 already!
indus is up to 20241215124618 already!
week is up to 20241215124746 already!
Data Processing Finished! Cost 0.00 Seconds
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
******************************** UPDATE MODELS ********************************
--------------------------------------------------------------------------------
***************************** PARSER TRAINING ARGS *****************************
--Process Queue : Data + Fit + Test
--Confi

24-12-15 18:40:36|MOD:display     |: Finish Process [Data], Cost 3.7 Secs
24-12-15 18:40:36|MOD:display     |: Start Process [Fit] at Sun Dec 15 18:40:36 2024!
24-12-15 18:40:36|MOD:display     |: Finish Process [Fit], Cost 0.0 Secs
24-12-15 18:40:36|MOD:display     |: Start Process [Test] at Sun Dec 15 18:40:36 2024!
24-12-15 18:40:36|MOD:display     |: Testing Mean Score(spearman):
24-12-15 18:40:36|MOD:display     |: Finish Process [Test], Cost 0.0 Secs
24-12-15 18:40:36|MOD:timer       |: Main Process Finished! Cost 3.8 Seconds
24-12-15 18:40:36|MOD:display     |: Model Specifics:
24-12-15 18:40:36|MOD:display     |: Start Process [Data] at Sun Dec 15 18:40:36 2024!


Pre-Norming method of [day] : {'divlast': True, 'histnorm': True}
--------------------------------------------------------------------------------
***************************** PARSER TRAINING ARGS *****************************
--Process Queue : Data + Fit + Test
--Confirm Resume Training!
--Model_name is set to gruRTN_day!
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
******************************* SETUP CALLBACKS *******************************
ResetOptimizer(num_reset=2,trigger=40,recover_level=1.0,speedup2x=True) , reset optimizer on some epoch (can speedup scheduler)
CallbackTimer(verbosity=2) , record time cost of callback hooks
EarlyStoppage(patience=20) , stop fitting when validation score cease to improve
ValidationConverge(patience=5,eps=1e-05) , stop fitting when valid_score converge
EarlyExitRetrain(earliest=10,max_attempt=4,lr_multiplier=[1, 0.1, 10, 0.01, 1

24-12-15 18:40:40|MOD:display     |: Finish Process [Data], Cost 3.7 Secs
24-12-15 18:40:40|MOD:display     |: Start Process [Fit] at Sun Dec 15 18:40:40 2024!
24-12-15 18:40:40|MOD:display     |: Finish Process [Fit], Cost 0.0 Secs
24-12-15 18:40:40|MOD:display     |: Start Process [Test] at Sun Dec 15 18:40:40 2024!
24-12-15 18:40:40|MOD:display     |: Testing Mean Score(spearman):
24-12-15 18:40:40|MOD:display     |: Finish Process [Test], Cost 0.0 Secs
24-12-15 18:40:40|MOD:timer       |: Main Process Finished! Cost 3.7 Seconds
24-12-15 18:40:40|MOD:display     |: Model Specifics:
24-12-15 18:40:40|MOD:display     |: Start Process [Data] at Sun Dec 15 18:40:40 2024!


Pre-Norming method of [day] : {'divlast': True, 'histnorm': True}
--------------------------------------------------------------------------------
***************************** PARSER TRAINING ARGS *****************************
--Process Queue : Data + Fit + Test
--Confirm Resume Training!
--Model_name is set to gru_avg!
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
******************************* SETUP CALLBACKS *******************************
ResetOptimizer(num_reset=2,trigger=40,recover_level=1.0,speedup2x=True) , reset optimizer on some epoch (can speedup scheduler)
CallbackTimer(verbosity=2) , record time cost of callback hooks
EarlyStoppage(patience=20) , stop fitting when validation score cease to improve
ValidationConverge(patience=5,eps=1e-05) , stop fitting when valid_score converge
EarlyExitRetrain(earliest=10,max_attempt=4,lr_multiplier=[1, 0.1, 10, 0.01, 100,

24-12-15 18:40:44|MOD:display     |: Finish Process [Data], Cost 3.7 Secs
24-12-15 18:40:44|MOD:display     |: Start Process [Fit] at Sun Dec 15 18:40:44 2024!
24-12-15 18:40:44|MOD:display     |: Finish Process [Fit], Cost 0.0 Secs
24-12-15 18:40:44|MOD:display     |: Start Process [Test] at Sun Dec 15 18:40:44 2024!
24-12-15 18:40:44|MOD:display     |: Testing Mean Score(spearman):
24-12-15 18:40:44|MOD:display     |: Finish Process [Test], Cost 0.0 Secs
24-12-15 18:40:44|MOD:timer       |: Main Process Finished! Cost 3.7 Seconds


Pre-Norming method of [day] : {'divlast': True, 'histnorm': True}
--------------------------------------------------------------------------------
