In [1]:
# 测试代码跑起来有没有问题，参数都设的很小，应该在一两分钟内执行完
from gp_main import main
# 各参数含义
# job_id     # 确定在哪个文件夹训练,-1代表新建,具体的数字是指定文件夹,但测试代码时统一在./pop/bendi
# start_iter # 从第几个大循环开始
# start_gen  # 从某个大循环的第几代种群开始
# test_code  # 是否只是测试代码有无bug,默认False
# noWith     # 是否取消所有计时器,默认False,有计时器时报错会出问题
profiler = main(job_id= -1 , start_iter=0 , start_gen=0 , test_code = True , noWith = False)
profiler.get_df(sort_on='cumtime' , highlight= None) # 看看各子程序耗时,用来优化

**Job Directory is : "./pop/bendi"
  --> Start New Training in "./pop/bendi"
**Device name: NVIDIA GeForce RTX 4090 , Available: True
-------------------- Data --------------------
  --> Directly load "./data/package/gp_data_package_test.pt"
**Load Data Done, Cost 0.11 Secs
  --> 2 factors, 2 raw data loaded!
**Cuda Memory: Free 23.2G, Allocated 0.1G, Reserved 0.1G, Re-collect 0.0G Cache!
==================== Iteration 0 start from Generation 0 ====================
-------------------- Setting --------------------
**Initialize GP Toolbox Done, Cost 0.00 Secs
-------------------- Evolution --------------------
**A Population(10) has been Initialized


  --> Evolve Generation 0: 100%|██████████| 10/10 [00:00<00:00, 26.18it/s]


  --> Survive 8 Offsprings, try Populating to 10 ones


  --> Evolve Generation 1: 100%|██████████| 10/10 [00:00<00:00, 109.51it/s]


**A HallofFame(5) has been Evolutionized
**2 Generations of Evolution Done, Cost 0.52 Secs, Freed CudaMemory 23.16G - > 23.10G
-------------------- Selection --------------------
**HallofFame(5) Contains 5 Promising Candidates with RankIR >= 1.50
  --> Hof__0/Elite__0 (IR-5.48|Corr+0.00): rank_add(sigmoid(cp),ts_top_avg(TURN,15,10))
  --> Cuda Memory: Free 22.5G, Allocated 0.1G, Reserved 0.7G, Re-collect 0.0G Cache!
  --> Hof__1/Elite__1 (IR-4.98|Corr+0.69): ts_xtop_yavg(cp,TURN,15,9)
  --> Cuda Memory: Free 22.5G, Allocated 0.1G, Reserved 0.7G, Re-collect 0.0G Cache!
  --> Hof__2/Elite__2 (IR-4.47|Corr+0.06): ts_cov(log(turn),ts_stddev(cp,9),15)
  --> Cuda Memory: Free 22.2G, Allocated 0.1G, Reserved 1.0G, Re-collect 0.0G Cache!
  --> Hof__4/Elite__3 (IR-3.39|Corr+0.46): ts_btm_avg(turn,15,4)
  --> Cuda Memory: Free 22.2G, Allocated 0.1G, Reserved 1.0G, Re-collect 0.0G Cache!
**An EliteGroup(4) has been Selected
  --> Memories of [gp_values , hof_elites , others] take 0.12G
**Selectio

type                           name  ncalls  ccalls  tottime  \
532   built-in-method  torch._C._linalg.linalg_lstsq     473       0   0.2196   
482          function                  neutralize_2d       1       0   0.3632   
491          function                       rank_pct      75       0   0.1265   
472          function                          allna      22       0   0.1035   
596          function                    load_tensor       8       0   0.1043   
...               ...                            ...     ...     ...      ...   
636          function                 create_mp_lock       1       0   0.0030   
635          function                       __exit__       8       0   0.0000   
634          function                      __enter__       8       0   0.0000   
633          function                        release      12       0   0.0000   
1569         function                       __init__       4       0   0.0000   

      cumtime                                              where  \
532    0.2196                                                      
482    0.1280  "/home/mengkjin/Workspace/learngp/gp_math_func...   
491    0.0775  "/home/mengkjin/Workspace/learngp/gp_math_func...   
472    0.0755  "/home/mengkjin/Workspace/learngp/gp_math_func...   
596    0.0623  "/home/mengkjin/.local/lib/python3.10/site-pac...   
...       ...                                                ...   
636    0.0000  "/home/mengkjin/.local/lib/python3.10/site-pac...   
635    0.0000  "/home/mengkjin/.local/lib/python3.10/site-pac...   
634    0.0000  "/home/mengkjin/.local/lib/python3.10/site-pac...   
633    0.0000  "/home/mengkjin/.local/lib/python3.10/site-pac...   
1569   0.0000                "/usr/lib/python3.10/codecs.py",186   

              memory                                          full_name  \
532                     <built-in method torch._C._linalg.linalg_lstsq>   
482   0x7f69ff060240  <code object neutralize_2d at 0x7f69ff060240, ...   
491   0x7f69ff061630  <code object rank_pct at 0x7f69ff061630, file ...   
472   0x7f69ff04b1b0  <code object allna at 0x7f69ff04b1b0, file "/h...   
596   0x7f6a76f73730  <code object load_tensor at 0x7f6a76f73730, fi...   
...              ...                                                ...   
636   0x7f6aa1b535d0  <code object create_mp_lock at 0x7f6aa1b535d0,...   
635   0x7f6aa1b53520  <code object __exit__ at 0x7f6aa1b53520, file ...   
634   0x7f6aa1b53470  <code object __enter__ at 0x7f6aa1b53470, file...   
633   0x7f6aa1b533c0  <code object release at 0x7f6aa1b533c0, file "...   
1569  0x7f6b6c5eb260  <code object __init__ at 0x7f6b6c5eb260, file ...   

                                                 caller  
532                                                None  
482   [(<method 'to' of 'torch._C._TensorBase' objec...  
491   [(<method 'to' of 'torch._C._TensorBase' objec...  
472   [(<method 'isfinite' of 'torch._C._TensorBase'...  
596   [(<code object default_restore_location at 0x7...  
...                                                 ...  
636   [(<built-in method builtins.hasattr>, 1, 0, 9....  
635   [(<code object release at 0x7f6aa1b533c0, file...  
634   [(<code object acquire at 0x7f6aa1b53310, file...  
633   [(<method 'release' of '_thread.RLock' objects...  
1569                                               None  

[1570 rows x 10 columns]

In [2]:
# 测试能不能继续训练
from gp_main import main
profiler = main(job_id= -1 , start_iter=0 , start_gen=1 , test_code = True , noWith = False)
profiler.get_df(sort_on='cumtime' , highlight= None) # 看看各子程序耗时,用来优化

**Job Directory is : "./pop/bendi"
  --> Continue Training in "./pop/bendi"
**Device name: NVIDIA GeForce RTX 4090 , Available: True
-------------------- Data --------------------
  --> Directly load "./data/package/gp_data_package_test.pt"
**Load Data Done, Cost 0.10 Secs
  --> 2 factors, 2 raw data loaded!
**Cuda Memory: Free 23.1G, Allocated 0.1G, Reserved 0.1G, Re-collect 0.0G Cache!
==================== Iteration 0 start from Generation 1 ====================
-------------------- Setting --------------------
**Initialize GP Toolbox Done, Cost 0.00 Secs
-------------------- Evolution --------------------


  --> Load HallofFame 0: 100%|██████████| 5/5 [00:00<00:00, 63.76it/s]


  --> Survive 8 Offsprings, try Populating to 10 ones


  --> Evolve Generation 1: 100%|██████████| 10/10 [00:00<00:00, 72.66it/s]


**A HallofFame(5) has been Evolutionized
**1 Generations of Evolution Done, Cost 0.26 Secs, Freed CudaMemory 23.04G - > 23.04G
-------------------- Selection --------------------
**HallofFame(5) Contains 5 Promising Candidates with RankIR >= 1.50
  --> Hof__0/Elite__0 (IR-5.48|Corr+0.00): rank_add(sigmoid(cp),ts_top_avg(TURN,15,10))
  --> Cuda Memory: Free 22.4G, Allocated 0.1G, Reserved 0.7G, Re-collect 0.0G Cache!
  --> Hof__1/Elite__1 (IR-4.47|Corr+0.06): ts_cov(log(turn),ts_stddev(cp,9),15)
  --> Cuda Memory: Free 22.2G, Allocated 0.1G, Reserved 1.0G, Re-collect 0.0G Cache!
  --> Hof__2/Elite__2 (IR-4.28|Corr+0.67): rank_mul(turn,cp)
  --> Cuda Memory: Free 22.2G, Allocated 0.1G, Reserved 1.0G, Re-collect 0.0G Cache!
  --> Hof__4/Elite__3 (IR-3.39|Corr+0.48): ts_btm_avg(turn,15,4)
  --> Cuda Memory: Free 22.2G, Allocated 0.1G, Reserved 1.0G, Re-collect 0.0G Cache!
**An EliteGroup(4) has been Selected
  --> Memories of [gp_values , hof_elites , others] take 0.12G
**Selection of Hall

type                           name  ncalls  ccalls  tottime  \
1487         function                         select     842       0   8.6008   
420          function                  neutralize_2d       1       0   0.2593   
467   built-in-method  torch._C._linalg.linalg_lstsq     473       0   0.1156   
410          function                          allna      19       0   0.0708   
535          function                    load_tensor       8       0   0.0955   
...               ...                            ...     ...     ...      ...   
682          function           _validate_skipfooter       2       0   0.0000   
681          function               _extract_dialect       2       0   0.0000   
680          function          _refine_defaults_read       2       0   0.0000   
679          function               _clean_na_values       2       0   0.0000   
1634         function                       __init__       2       0   0.0000   

      cumtime                                              where  \
1487   8.5709  "/home/mengkjin/.local/lib/python3.10/site-pac...   
420    0.1270  "/home/mengkjin/Workspace/learngp/gp_math_func...   
467    0.1156                                                      
410    0.0687  "/home/mengkjin/Workspace/learngp/gp_math_func...   
535    0.0585  "/home/mengkjin/.local/lib/python3.10/site-pac...   
...       ...                                                ...   
682    0.0000  "/home/mengkjin/.local/lib/python3.10/site-pac...   
681    0.0000  "/home/mengkjin/.local/lib/python3.10/site-pac...   
680    0.0000  "/home/mengkjin/.local/lib/python3.10/site-pac...   
679    0.0000  "/home/mengkjin/.local/lib/python3.10/site-pac...   
1634   0.0000                "/usr/lib/python3.10/codecs.py",260   

              memory                                          full_name  \
1487  0x7f6b6b9e1840  <code object select at 0x7f6b6b9e1840, file "/...   
420   0x7f69ff060240  <code object neutralize_2d at 0x7f69ff060240, ...   
467                     <built-in method torch._C._linalg.linalg_lstsq>   
410   0x7f69ff04b1b0  <code object allna at 0x7f69ff04b1b0, file "/h...   
535   0x7f6a76f73730  <code object load_tensor at 0x7f6a76f73730, fi...   
...              ...                                                ...   
682   0x7f6aa1de63f0  <code object _validate_skipfooter at 0x7f6aa1d...   
681   0x7f6aa1de6130  <code object _extract_dialect at 0x7f6aa1de613...   
680   0x7f6aa1de6080  <code object _refine_defaults_read at 0x7f6aa1...   
679   0x7f6aa1de5e70  <code object _clean_na_values at 0x7f6aa1de5e7...   
1634  0x7f6b6c5ebc00  <code object __init__ at 0x7f6b6c5ebc00, file ...   

                                                 caller  
1487  [(<method 'append' of 'list' objects>, 843, 0,...  
420   [(<built-in method builtins.isinstance>, 1, 0,...  
467                                                None  
410   [(<method 'isfinite' of 'torch._C._TensorBase'...  
535   [(<method 'decode' of 'bytes' objects>, 8, 0, ...  
...                                                 ...  
682   [(<method 'get' of 'dict' objects>, 2, 0, 3.05...  
681   [(<method 'get' of 'dict' objects>, 2, 0, 3.14...  
680   [(<code object check_dtype_backend at 0x7f6aa2...  
679                                                None  
1634                                               None  

[1635 rows x 10 columns]

In [1]:
# 真实测试，job_id=-1代表在新的pop的子文件夹中保存结果，如果强制要求在已有文件夹基础上继续训练，代码可能要再修改
from gp_main import main
profiler = main(job_id= 0 , start_iter=0 , start_gen=0 , test_code = False , noWith = True)

**Job Directory is : "./pop/0"
  --> Start New Training in "./pop/0"
**Device name: NVIDIA GeForce RTX 4090 , Available: True
**Cuda Memory: Free 20.9G, Allocated 2.3G, Reserved 2.3G, Re-collect 0.0G Cache!
==================== Iteration 0 start from Generation 0 ====================
['_I_0_(ma(sign(ts_rankcorr__2__(LP, AMT, 3)), 2))', 'add(vp, vol)', 'div(ts_top_avg__0__(amt, 15, 3), mul(adv60, lp))', 'log__0__(_I_1_(_I_1_(_I_1_(_I_1_(EP)))))', 'log__0__(_I_1_(_I_1_(_I_1_(_I_1_(VP)))))', 'log__0__(DP)', 'log(ts_argmin__0__(_I_1_(_I_1_(_I_1_(OP))), _I_3_(_I_3_(_I_3_(3)))))', 'log(vol)', 'ma__1__(_I_1_(_I_1_(BP)), 8)', 'ma__1__(_I_1_(VP), 6)', 'ma__1__(ADV20, 8)', 'ma__1__(ADV60, 2)', 'ma__2__(TURN, 20)', 'ma__0__(cp, _I_4_(10))', 'ma(ocfp, 7)', 'ma(ts_beta__1__(RTN, ep, 3), _I_3_(10))', 'ma__0__(ts_corr__1__(_I_1_(_I_1_(_I_1_(ADV20))), div(ts_beta(pctchg(DP, 3), ts_dwdif__0__(lp, AMT, 40), _I_3_(3)), log__0__(_I_1_(VP))), _I_3_(_I_3_(_I_3_(7)))), _I_4_(_I_4_(_I_4_(_I_4_(10)))))', 'mul(

  --> Evolve Generation 0: 100%|██████████| 100/100 [00:11<00:00,  9.01it/s]
Traceback (most recent call last):
  File "/home/mengkjin/Workspace/learngp/gp_main.py", line 492, in gp_evolution
    offspring = toolbox.syxpop2indpop(offspring)
  File "/home/mengkjin/Workspace/learngp/gp_utils.py", line 197, in syxpop2indpop
    return [toolbox.syx2ind(ind) for ind in population]
  File "/home/mengkjin/Workspace/learngp/gp_utils.py", line 197, in <listcomp>
    return [toolbox.syx2ind(ind) for ind in population]
  File "/home/mengkjin/Workspace/learngp/gp_utils.py", line 163, in syx2ind
    return toolbox.str2ind(x.ind_name)
  File "/home/mengkjin/Workspace/learngp/gp_utils.py", line 153, in str2ind
    return creator.Individual.from_string(x , pset=pset_ind) # type:ignore
  File "/home/mengkjin/.local/lib/python3.10/site-packages/deap/gp.py", line 129, in from_string
    raise TypeError("Primitive {} return type {} does not "
TypeError: Primitive <deap.gp.Terminal object at 0x7f4a4030e100

Error Type : <class 'TypeError'>
Error Value : Primitive <deap.gp.Terminal object at 0x7f4a4030e100> return type <class 'gp_utils.int3'> does not match the expected one: <class 'gp_utils.int2'>.
Error Type : <class 'TypeError'>
Error Value : Primitive <deap.gp.Terminal object at 0x7f4a4030e100> return type <class 'gp_utils.int3'> does not match the expected one: <class 'gp_utils.int2'>.
Error Type : <class 'TypeError'>
Error Value : Primitive <deap.gp.Terminal object at 0x7f4a4030e100> return type <class 'gp_utils.int3'> does not match the expected one: <class 'gp_utils.int2'>.


TypeError: Primitive <deap.gp.Terminal object at 0x7f4a4030e100> return type <class 'gp_utils.int3'> does not match the expected one: <class 'gp_utils.int2'>.

In [ ]:
# 给定因子表达式,得到全样本区间的因子值
from gp_main import *
from gp_utils import *

func = gp_factor_generator(test_code = True)
func('ts_corr(cp, CP, 7)')


**Job Directory is : "./pop/bendi"
-------------------- Data --------------------
  --> Directly load "./data/package/gp_data_package_test.pt"
**Load Data Done, Cost 0.07 Secs
  --> 2 factors, 2 raw data loaded!


tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [-0.0657,     nan,  0.0073,  ..., -0.0612, -0.0417,  0.0049],
        [-0.0038, -0.0206,  0.0071,  ..., -0.0463,     nan,  0.0068],
        [-0.0061, -0.0229,  0.0036,  ..., -0.0530,     nan, -0.0234]])

In [ ]:
class EmptyTimer:
    def __enter__(self):
        pass
    def __exit__(self, type, value, trace):
        print(type , value)
        print(trace)

with EmptyTimer():
    raise KeyError('aaa')
a = 1

<class 'KeyError'> 'aaa'


KeyError: 'aaa'

In [ ]:
a

NameError: name 'a' is not defined

In [ ]:
from gp_main import *
a = gp_multifactor(0)

Loading factor parquets: 100%|██████████| 5/5 [00:06<00:00,  1.21s/it]


Beware! future information used!


In [ ]:
import torch
a = torch.Tensor([torch.nan,torch.inf])
b = a.nan_to_num_(0,0,0)
a is b

True

In [ ]:
import torch
a = torch.rand(100 , 10)
mat = a.T.mm(a)
svd = torch.linalg.svd(b)

In [ ]:
torch.diag(svd.S)

tensor([[258.6961,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000],
        [  0.0000,  13.2971,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,  11.1351,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  10.1185,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   8.8712,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   8.3178,   0.0000,
           0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   6.8591,
           0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           6.7035,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,

In [ ]:
vector = svd.U @ a.T

In [ ]:
b

tensor([[29.4512, 22.6779, 23.7730, 23.2615, 21.3629, 26.8521, 24.4361, 20.6758,
         22.4063, 23.8412],
        [22.6779, 36.2933, 24.4314, 28.7911, 24.9064, 28.7055, 28.5578, 24.7060,
         23.5809, 28.0866],
        [23.7730, 24.4314, 32.7650, 24.9694, 21.0530, 27.7802, 26.7312, 23.1877,
         23.8526, 25.5734],
        [23.2615, 28.7911, 24.9694, 35.4707, 22.6927, 28.0770, 27.6353, 23.5558,
         23.9529, 27.7252],
        [21.3629, 24.9064, 21.0530, 22.6927, 27.1140, 24.2808, 24.4535, 20.1986,
         21.2453, 22.8292],
        [26.8521, 28.7055, 27.7802, 28.0770, 24.2808, 37.6412, 28.1828, 25.9771,
         26.1574, 29.6774],
        [24.4361, 28.5578, 26.7312, 27.6353, 24.4535, 28.1828, 36.7733, 25.7596,
         25.9066, 27.3087],
        [20.6758, 24.7060, 23.1877, 23.5558, 20.1986, 25.9771, 25.7596, 30.6778,
         20.5936, 25.3841],
        [22.4063, 23.5809, 23.8526, 23.9529, 21.2453, 26.1574, 25.9066, 20.5936,
         31.1825, 24.3746],
        [23.8412, 2

In [ ]:
vector.mm(vector.T) * torch.diag(svd.S)

tensor([[8210.5898,   -0.0000,    0.0000,   -0.0000,   -0.0000,   -0.0000,
           -0.0000,   -0.0000,   -0.0000,    0.0000],
        [  -0.0000,  189.9778,   -0.0000,    0.0000,    0.0000,    0.0000,
            0.0000,    0.0000,    0.0000,   -0.0000],
        [   0.0000,   -0.0000,  408.9219,   -0.0000,   -0.0000,   -0.0000,
           -0.0000,   -0.0000,   -0.0000,    0.0000],
        [  -0.0000,    0.0000,   -0.0000,   61.9093,    0.0000,    0.0000,
            0.0000,    0.0000,    0.0000,   -0.0000],
        [  -0.0000,    0.0000,   -0.0000,    0.0000,  911.9656,    0.0000,
            0.0000,    0.0000,    0.0000,   -0.0000],
        [  -0.0000,    0.0000,   -0.0000,    0.0000,    0.0000,   77.5556,
            0.0000,    0.0000,    0.0000,   -0.0000],
        [  -0.0000,    0.0000,   -0.0000,    0.0000,    0.0000,    0.0000,
          104.5550,    0.0000,    0.0000,   -0.0000],
        [  -0.0000,    0.0000,   -0.0000,    0.0000,    0.0000,    0.0000,
            0.0000,  4

In [ ]:
from gp_main import *
from gp_utils import *
gp_space = gp_namespace(gp_parameters(False , -1 , True))

toolbox = gpHandler.Toolbox(eval_func = evaluate , **gp_space)
population = gp_population(toolbox , **gp_space)
'ts_corr(TURN, TURN, 7)'

**Device name: NVIDIA GeForce RTX 4090 , Available: True
  --> Pop directory is : "./pop/2"
**Load Data Done, cost 2.28 secs
**Cuda Memory: Free 1.4G, Allocated 16.6G, Reserved 21.8G


'ts_corr(TURN, TURN, 7)'

In [2]:
import operator , time , joblib , os , gc , itertools , re , traceback
import numpy as np
import pandas as pd
import torch
from argparse import Namespace
from deap import base , creator , tools , gp
from copy import deepcopy
import gp_math_func as MF
import gp_factor_func as FF

class Fac(torch.Tensor): pass
class Raw(torch.Tensor): pass
class int1(int): pass
class int2(int): pass
class int3(int): pass
class int4(int): pass
class int5(int): pass
class float1(float): pass

pset = gp.PrimitiveSetTyped('main', [Fac] * 2 + [Raw] * 1, Fac)

pset.addEphemeralConstant(f'int1{0}', lambda: np.random.randint(1,10+1), int1) # random int must > 0
pset.addEphemeralConstant(f'int2{0}', lambda: np.random.randint(2,10+1), int2) # random int must > 1
#for v in [10 , 15 , 20 , 40]:  pset.addTerminal(v, int3)
#for v in [10 , 20]:  pset.addTerminal(v, int4)
#for v in [60 , 120 , 180 , 200 , 240]: pset.addTerminal(v, int5)

pset.addPrimitive(MF.add , [Fac , float] , Fac)

In [4]:
gp.compile('add(ARG0,ARG2)',pset=pset)(torch.rand(10),1,2)

tensor([2.8089, 2.0959, 2.7645, 2.0856, 2.8076, 2.8209, 2.1527, 2.2615, 2.5122,
        2.1361])

In [7]:
pset.primitives.__delitem__(Fac)

In [8]:
pset.primitives

defaultdict(list,
            {__main__.Raw: [],
             __main__.int1: [],
             __main__.int2: [],
             float: []})

In [10]:
import torch
import gp_math_func as MF
class Fac(torch.Tensor): pass
class Raw(torch.Tensor): pass
a = Raw(list(range(10)))

In [1]:
import operator , time , joblib , os , gc , itertools , re , traceback
import numpy as np
import pandas as pd
import torch
from argparse import Namespace
from deap import base , creator , tools , gp
from copy import deepcopy
import gp_math_func as MF
import gp_factor_func as FF

class int1(int): pass

pset = gp.PrimitiveSetTyped('main', [torch.Tensor] * 2, torch.Tensor)
pset.addEphemeralConstant('int0',lambda: np.random.randint(2,10+1), int1)
creator.create('FitnessMin', base.Fitness, weights=(+1.0,))   # 优化问题：单目标优化，weights为单元素；+1表明适应度越大，越容易存活
creator.create('Individual', gp.PrimitiveTree, fitness=creator.FitnessMin, ) # type:ignore
pset.addPrimitive(MF.add , [torch.Tensor , int] , torch.Tensor)

In [20]:
b = creator.Individual.from_string('(add((ARG0),3))' , pset = pset)

In [28]:
'(add((ARG0),3))'.split(r'.')

['(add((ARG0),3))']

In [12]:
import re

def assert_string_pattern(input_string):
    pattern = r'^_I_[0-9]+_$'
    
    if re.match(pattern, input_string):
        print(f"The string '{input_string}' matches the pattern '_I_[0-9]+_'.")
    else:
        print(f"The string '{input_string}' does not match the pattern '_I_[0-9]+_'.")

# Test the function with different strings
assert_string_pattern('_I_123_')  # This should match
assert_string_pattern('_I_abc_')  # This should not match
assert_string_pattern('123_I_456')  # This should not match


The string '1_I_123_' does not match the pattern '_I_[0-9]+_'.
The string '_I_abc_' does not match the pattern '_I_[0-9]+_'.
The string '123_I_456' does not match the pattern '_I_[0-9]+_'.


In [19]:
a = [1,3,4,5,6,9,10]
a = [i for i in a if i-1 not in a]
print(a)

[1, 3, 9]


In [18]:
a = [i for i in a if i-1 not in a]
print(a)

[1, 3, 6, 9]


In [ ]:
re.fullmatch()

In [8]:
isinstance(type(torch.square(a)) , Fac)

False

In [13]:
type(MF.ts_corr(Fac(torch.rand(100,100)),Raw(torch.rand(100,100)) , 10))

TypeError: unsupported operand type(s) for +: 'Fac' and 'Raw'