In [2]:
# 测试代码跑起来有没有问题，参数都设的很小，应该在一两分钟内执行完
from gp_main import main
# 各参数含义
# job_id     # 确定在哪个文件夹训练,-1代表新建,具体的数字是指定文件夹,但测试代码时统一在./pop/bendi
# start_iter # 从第几个大循环开始
# start_gen  # 从某个大循环的第几代种群开始
# test_code  # 是否只是测试代码有无bug,默认False
# noWith     # 是否取消所有计时器,默认False,有计时器时报错会出问题
profiler = main(job_id= -1 , start_iter=0 , start_gen=0 , test_code = True , noWith = True , neut_method = 1)
profiler.get_df(sort_on='cumtime' , highlight= None)[:10] # 看看各子程序耗时,用来优化

**Job Directory is : "./pop/bendi"
  --> Start New Training in "./pop/bendi"
**Device name: NVIDIA GeForce RTX 4090 , Available: True
**Cuda Memory: Free 23.1G, Allocated 0.0G, Reserved 0.0G, Re-collect 0.1G Cache!
-------------------- Data --------------------
  --> Directly load "./data/package/gp_data_package_test.pt"
**Load Data Done, Cost 0.05 Secs
  --> 2 factors, 2 raw data loaded!
==================== Iteration 0 start from Generation 0 ====================
-------------------- Residual --------------------
**Cuda Memory: Free 23.1G, Allocated 0.1G, Reserved 0.1G, Re-collect 0.0G Cache!
**Update Residual Labels Done, Cost 0.02 Secs, Freed CudaMemory 23.06G - > 23.06G
-------------------- Setting --------------------
**Initialize GP Toolbox Done, Cost 0.00 Secs
-------------------- Evolution --------------------
**A Population(6) has been Initialized


  --> Evolve Generation 0 MaxIRres-4.73|MaxIRraw-4.73: 100%|██████████| 6/6 [00:00<00:00, 76.05it/s]


  --> Survive 3 Offsprings, try Populating to 6 ones


  --> Evolve Generation 1 MaxIRres-4.73|MaxIRraw-4.73: 100%|██████████| 6/6 [00:00<00:00, 88.57it/s]


**A HallofFame(2) has been Evolutionized
**2 Generations of Evolution Done, Cost 0.17 Secs, Freed CudaMemory 23.06G - > 23.06G
-------------------- Selection --------------------
**HallofFame(2) Contains 2 Promising Candidates with RankIR >= 3.00
  --> Hof__0/Elite__0 (IR-4.73|Corr+0.00): ts_top_avg(turn,10,1)
  --> Hof__1/Elite__1 (IR-3.75|Corr+0.28): ma(cp,20)
**An EliteGroup(2) has been Selected
  --> Cuda Memories of "gp_inputs" take 0.0376G
  --> Cuda Memories of "elites"    take 0.0188G
  --> Cuda Memories of "tensors"   take 0.0000G
**Selection of HallofFame Done, Cost 0.09 Secs, Freed CudaMemory 23.06G - > 23.06G
==================== Iteration 1 start from Generation 0 ====================
-------------------- Residual --------------------
tensor([0.7704, 1.0000], device='cuda:0')
  -> Elites(2) Shrink to SvdElites(1)
  -> Neutra has 1 Elements
**Cuda Memory: Free 23.0G, Allocated 0.1G, Reserved 0.1G, Re-collect 0.1G Cache!
**Update Residual Labels Done, Cost 0.30 Secs, Freed C

  --> Evolve Generation 0 MaxIRres-3.22|MaxIRraw-3.12: 100%|██████████| 6/6 [00:00<00:00, 86.99it/s]


  --> Survive 5 Offsprings, try Populating to 6 ones


  --> Evolve Generation 1 MaxIRres-3.22|MaxIRraw-4.41: 100%|██████████| 6/6 [00:00<00:00, 65.62it/s]

**A HallofFame(2) has been Evolutionized
**2 Generations of Evolution Done, Cost 0.18 Secs, Freed CudaMemory 23.04G - > 23.04G
-------------------- Selection --------------------
**HallofFame(2) Contains 2 Promising Candidates with RankIR >= 2.70


  --> Hof__0/Elite__2 (IR-3.22|Corr+0.00): ts_btm_avg(TURN,40,1)
**An EliteGroup(1) has been Selected
  --> Cuda Memories of "gp_inputs" take 0.0376G
  --> Cuda Memories of "elites"    take 0.0094G
  --> Cuda Memories of "tensors"   take 0.0000G
**Selection of HallofFame Done, Cost 0.09 Secs, Freed CudaMemory 23.04G - > 23.04G
==================== Total Time Cost :0 hours 0.0 ====================
   Residual  Setting  Evolution  Selection  AvgVarAnd  AvgCompile  AvgEval     All
0    0.0226   0.0042     0.1661     0.0904     0.0002  7.7946...    0.0053  0.2926
1    0.2965   0.0029     0.1830     0.0877     0.0004  7.9989...    0.0079  0.5780


type                           name  ncalls  ccalls  tottime  \
445         function                  neutralize_2d       2       0   0.2312   
493  built-in-method  torch._C._linalg.linalg_lstsq     473       0   0.0996   
435         function                          allna      24       0   0.0985   
202           method                        'equal'      45       0   0.0817   
549         function                          _save       8       0   0.1189   
161           method                        'copy_'      17       0   0.0680   
177  built-in-method      torch._C._cuda_emptyCache      26       0   0.0452   
555         function                    load_tensor      10       0   0.0624   
89            method                      'acquire'     323       0   0.0288   
193           method                           'to'     140       0   0.0185   

     cumtime                                              where  \
445   0.1169  "/home/mengkjin/Workspace/learngp/gp_math_func...   
493   0.0996                                                      
435   0.0957  "/home/mengkjin/Workspace/learngp/gp_math_func...   
202   0.0817                             'torch._C._TensorBase'   
549   0.0685  "/home/mengkjin/.local/lib/python3.10/site-pac...   
161   0.0680                             'torch._C.StorageBase'   
177   0.0452                                                      
555   0.0373  "/home/mengkjin/.local/lib/python3.10/site-pac...   
89    0.0288                                     '_thread.lock'   
193   0.0185                             'torch._C._TensorBase'   

             memory                                          full_name  \
445  0x7f0967e6c5b0  <code object neutralize_2d at 0x7f0967e6c5b0, ...   
493                    <built-in method torch._C._linalg.linalg_lstsq>   
435  0x7f0967e5f470  <code object allna at 0x7f0967e5f470, file "/h...   
202                  <method 'equal' of 'torch._C._TensorBase' obje...   
549  0x7f09dfd82a20  <code object _save at 0x7f09dfd82a20, file "/h...   
161                  <method 'copy_' of 'torch._C.StorageBase' obje...   
177                        <built-in method torch._C._cuda_emptyCache>   
555  0x7f09dfd83940  <code object load_tensor at 0x7f09dfd83940, fi...   
89                        <method 'acquire' of '_thread.lock' objects>   
193                    <method 'to' of 'torch._C._TensorBase' objects>   

                                                caller  
445  [(<code object betas_torch at 0x7f0967e6c190, ...  
493                                               None  
435  [(<method 'isfinite' of 'torch._C._TensorBase'...  
202                                               None  
549  [(<code object cpu at 0x7f09dfd43cb0, file "/h...  
161                                               None  
177                                               None  
555  [(<code object _typed_storage at 0x7f09e01f024...  
89                                                None  
193                                               None

In [5]:
# 测试能不能继续训练
from gp_main import main
profiler = main(job_id= -1 , start_iter=1 , start_gen=0 , test_code = True , noWith = False , neut_method = 1)
profiler.get_df(sort_on='cumtime' , highlight= None)[:10] # 看看各子程序耗时,用来优化

**Job Directory is : "./pop/bendi"
  --> Continue Training in "./pop/bendi"
**Device name: NVIDIA GeForce RTX 4090 , Available: True
**Cuda Memory: Free 22.9G, Allocated 0.3G, Reserved 0.3G, Re-collect 0.0G Cache!
-------------------- Data --------------------
  --> Directly load "./data/package/gp_data_package_test.pt"
**Load Data Done, Cost 0.09 Secs
  --> 2 factors, 2 raw data loaded!
==================== Iteration 1 start from Generation 0 ====================
-------------------- Residual --------------------
tensor([0.7704, 1.0000], device='cuda:0')
  -> Elites(2) Shrink to SvdElites(1)
  -> Neutra has 1 Elements
**Cuda Memory: Free 22.8G, Allocated 0.4G, Reserved 0.4G, Re-collect 0.1G Cache!
**Update Residual Labels Done, Cost 0.42 Secs, Freed CudaMemory 22.80G - > 22.78G
-------------------- Setting --------------------
**Initialize GP Toolbox Done, Cost 0.00 Secs
-------------------- Evolution --------------------
**A Population(6) has been Initialized


  --> Evolve Generation 0 MaxIRres-2.04|MaxIRraw-2.24: 100%|██████████| 6/6 [00:00<00:00, 117.07it/s]


  --> Survive 3 Offsprings, try Populating to 6 ones


  --> Evolve Generation 1 MaxIRres-3.30|MaxIRraw-4.05: 100%|██████████| 6/6 [00:00<00:00, 67.83it/s]

**A HallofFame(2) has been Evolutionized
**2 Generations of Evolution Done, Cost 0.16 Secs, Freed CudaMemory 22.78G - > 22.78G
-------------------- Selection --------------------
**HallofFame(2) Contains 1 Promising Candidates with RankIR >= 2.70


  --> Hof__0/Elite__2 (IR-3.30|Corr+0.00): cp
**An EliteGroup(1) has been Selected
  --> Cuda Memories of "gp_inputs" take 0.0376G
  --> Cuda Memories of "elites"    take 0.0094G
  --> Cuda Memories of "tensors"   take 0.0000G
**Selection of HallofFame Done, Cost 0.07 Secs, Freed CudaMemory 22.78G - > 22.78G
==================== Total Time Cost :0 hours 0.0 ====================
   Residual  Setting  Evolution  Selection  AvgVarAnd  AvgCompile  AvgEval     All
0    0.4166   0.0029     0.1585     0.0718     0.0002  7.5835...    0.0055  0.6656


type                           name  ncalls  ccalls  tottime  \
430         function                  neutralize_2d       1       0   0.3407   
472  built-in-method  torch._C._linalg.linalg_lstsq     473       0   0.1475   
530         function                    load_tensor      10       0   0.1176   
150           method                        'copy_'      13       0   0.0440   
524         function                          _save       5       0   0.0570   
191           method                        'equal'      24       0   0.0351   
420         function                          allna      12       0   0.0350   
203           method                  'nanquantile'      24       0   0.0238   
166  built-in-method      torch._C._cuda_emptyCache      11       0   0.0201   
214           method                          'sum'     622       0   0.0183   

     cumtime                                              where  \
430   0.1696  "/home/mengkjin/Workspace/learngp/gp_math_func...   
472   0.1475                                                      
530   0.0836  "/home/mengkjin/.local/lib/python3.10/site-pac...   
150   0.0440                             'torch._C.StorageBase'   
524   0.0352  "/home/mengkjin/.local/lib/python3.10/site-pac...   
191   0.0351                             'torch._C._TensorBase'   
420   0.0309  "/home/mengkjin/Workspace/learngp/gp_math_func...   
203   0.0238                             'torch._C._TensorBase'   
166   0.0201                                                      
214   0.0183                             'torch._C._TensorBase'   

             memory                                          full_name  \
430  0x7f0967e6c5b0  <code object neutralize_2d at 0x7f0967e6c5b0, ...   
472                    <built-in method torch._C._linalg.linalg_lstsq>   
530  0x7f09dfd83940  <code object load_tensor at 0x7f09dfd83940, fi...   
150                  <method 'copy_' of 'torch._C.StorageBase' obje...   
524  0x7f09dfd82a20  <code object _save at 0x7f09dfd82a20, file "/h...   
191                  <method 'equal' of 'torch._C._TensorBase' obje...   
420  0x7f0967e5f470  <code object allna at 0x7f0967e5f470, file "/h...   
203                  <method 'nanquantile' of 'torch._C._TensorBase...   
166                        <built-in method torch._C._cuda_emptyCache>   
214                   <method 'sum' of 'torch._C._TensorBase' objects>   

                                                caller  
430  [(<method 'squeeze_' of 'torch._C._TensorBase'...  
472                                               None  
530  [(<code object default_restore_location at 0x7...  
150                                               None  
524  [(<built-in method builtins.sorted>, 5, 0, 1.1...  
191                                               None  
420  [(<method 'any' of 'torch._C._TensorBase' obje...  
203                                               None  
166                                               None  
214                                               None

In [1]:
# 真实测试，job_id=-1代表在新的pop的子文件夹中保存结果，如果强制要求在已有文件夹基础上继续训练，代码可能要再修改
from gp_main import main
profiler = main(job_id= 1 , start_iter=2 , start_gen=0 , test_code = False , noWith = True , neut_method = 0)

**Job Directory is : "./pop/1"
  --> Continue Training in "./pop/1"
**Device name: NVIDIA GeForce RTX 4090 , Available: True
**Cuda Memory: Free 23.3G, Allocated 0.0G, Reserved 0.0G, Re-collect 0.0G Cache!
-------------------- Data --------------------
**Load Data Done, Cost 2.23 Secs
==================== Iteration 2 start from Generation 0 ====================
-------------------- Residual --------------------
tensor([0.2571, 0.3327, 0.3922, 0.4334, 0.4709, 0.4980, 0.5218, 0.5404, 0.5571,
        0.5723, 0.5867, 0.6007, 0.6140, 0.6265, 0.6382, 0.6495, 0.6601, 0.6701,
        0.6798, 0.6888, 0.6976, 0.7057, 0.7136, 0.7213, 0.7289, 0.7362, 0.7433,
        0.7502, 0.7568, 0.7633, 0.7695, 0.7756, 0.7815, 0.7873, 0.7930, 0.7984,
        0.8037, 0.8090, 0.8140, 0.8191, 0.8239, 0.8286, 0.8332, 0.8377, 0.8421,
        0.8463, 0.8505, 0.8546, 0.8586, 0.8626, 0.8664, 0.8702, 0.8739, 0.8775,
        0.8811, 0.8845, 0.8878, 0.8912, 0.8945, 0.8977, 0.9008, 0.9038, 0.9067,
        0.9096, 0.9125, 0

  --> Evolve Generation 0 MaxIRres-7.29|MaxIRraw-5.45: 100%|██████████| 3000/3000 [07:11<00:00,  6.96it/s]


  --> Survive 1447 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 1 MaxIRres-7.27|MaxIRraw-5.45: 100%|██████████| 3000/3000 [06:48<00:00,  7.35it/s]


  --> Survive 1500 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 2 MaxIRres-7.25|MaxIRraw+5.60: 100%|██████████| 3000/3000 [06:31<00:00,  7.66it/s]


  --> Survive 1454 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 3 MaxIRres-7.29|MaxIRraw+5.59: 100%|██████████| 3000/3000 [06:34<00:00,  7.60it/s]


  --> Survive 1480 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 4 MaxIRres-7.28|MaxIRraw+5.59: 100%|██████████| 3000/3000 [06:27<00:00,  7.75it/s]


  --> Survive 1480 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 5 MaxIRres-7.20|MaxIRraw+5.60: 100%|██████████| 3000/3000 [06:28<00:00,  7.73it/s]


**A HallofFame(500) has been Evolutionized
**6 Generations of Evolution Done, Cost 2405.93 Secs, Freed CudaMemory 19.01G - > 19.00G
-------------------- Selection --------------------
**HallofFame(500) Contains 414 Promising Candidates with RankIR >= 3.00
  --> Hof__0/Elite235 (IR-7.29|Corr+0.00): ts_max(TURN,2)
  --> Hof__4/Elite236 (IR-7.22|Corr+0.69): rank(sqrt(TURN))
  --> Hof_19/Elite237 (IR-5.95|Corr+0.49): sigmoid(ts_dwdif(ts_min(TURN,4),ADV20,40))
  --> Hof_20/Elite238 (IR-5.78|Corr+0.64): ts_max(power(ts_xtop_yavg(ts_argmax(vol,7),TURN,15,1),1.02),5)
  --> Hof_31/Elite239 (IR-4.99|Corr+0.55): ts_dwdif(RTN,DP,30)
  --> Hof_34/Elite240 (IR+4.80|Corr-0.66): rank_sub(sqrt(EP),ts_btm_avg(TURN,10,1))
  --> Hof_53/Elite241 (IR-4.49|Corr+0.09): ts_corr(VOL,TURN,8)
  --> Hof_55/Elite242 (IR+4.44|Corr-0.62): ts_dwdif(log(HP),TURN,15)
  --> Hof_60/Elite243 (IR-4.36|Corr+0.69): ts_delay(log(TURN),8)
  --> Hof_65/Elite244 (IR-4.32|Corr+0.66): rank_sub(ts_dwdif(TURN,hp,40),ts_delta(bp,2))
 

  --> Evolve Generation 0 MaxIRres-7.68|MaxIRraw-5.46: 100%|██████████| 3000/3000 [07:10<00:00,  6.96it/s]


  --> Survive 1461 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 1 MaxIRres-7.68|MaxIRraw-5.46: 100%|██████████| 3000/3000 [06:34<00:00,  7.60it/s]


  --> Survive 1462 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 2 MaxIRres-7.68|MaxIRraw-5.45: 100%|██████████| 3000/3000 [06:26<00:00,  7.75it/s]


  --> Survive 1473 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 3 MaxIRres-7.68|MaxIRraw-5.45: 100%|██████████| 3000/3000 [06:26<00:00,  7.76it/s]


  --> Survive 1484 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 4 MaxIRres-7.68|MaxIRraw+6.50: 100%|██████████| 3000/3000 [06:23<00:00,  7.82it/s]


  --> Survive 1463 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 5 MaxIRres-7.68|MaxIRraw+6.50: 100%|██████████| 3000/3000 [06:20<00:00,  7.88it/s]


**A HallofFame(500) has been Evolutionized
**6 Generations of Evolution Done, Cost 2368.80 Secs, Freed CudaMemory 19.07G - > 19.07G
-------------------- Selection --------------------
**HallofFame(500) Contains 500 Promising Candidates with RankIR >= 3.00
  --> Hof__0/Elite300 (IR-7.68|Corr+0.00): log(TURN)
  --> Hof_17/Elite301 (IR-6.43|Corr+0.69): ts_max(ts_xtop_yavg(AMT,TURN,10,1),9)
  --> Hof_23/Elite302 (IR-5.98|Corr+0.48): ts_dwdif(sqrt(RTN),ts_xbtm_yavg(RTN,EP,20,4),30)
  --> Hof_29/Elite303 (IR-5.93|Corr+0.67): log(rank(ts_xtop_yavg(RTN,TURN,15,1)))
  --> Hof_31/Elite304 (IR+5.91|Corr-0.68): rank_sub(ts_rankcorr(ts_rng_dif(sqrt(ep),10,7),ts_btm_avg(ADV20,15,3),5),ts_xtop_yavg(RTN,TURN,15,6))
  --> Hof_34/Elite305 (IR-5.70|Corr+0.68): ts_dwdif(RTN,DP,20)
  --> Hof_36/Elite306 (IR-5.65|Corr+0.65): rank(ts_rng_dif(RTN,15,1))
  --> Hof_62/Elite307 (IR+5.30|Corr-0.64): ts_dwdif(ts_argmin(vp,7),TURN,30)
  --> Hof_66/Elite308 (IR-5.28|Corr+0.45): ts_corr(TURN,power(AMT,0.48),2)
  --> 

  --> Evolve Generation 0 MaxIRres-7.65|MaxIRraw-5.44: 100%|██████████| 3000/3000 [07:20<00:00,  6.82it/s]


  --> Survive 1463 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 1 MaxIRres-7.60|MaxIRraw-5.82: 100%|██████████| 3000/3000 [06:58<00:00,  7.16it/s]


  --> Survive 1478 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 2 MaxIRres-7.60|MaxIRraw-5.71: 100%|██████████| 3000/3000 [06:50<00:00,  7.31it/s]


  --> Survive 1478 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 3 MaxIRres-7.60|MaxIRraw-5.71: 100%|██████████| 3000/3000 [06:35<00:00,  7.58it/s]


  --> Survive 1482 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 4 MaxIRres-7.60|MaxIRraw-5.60: 100%|██████████| 3000/3000 [06:26<00:00,  7.76it/s]


  --> Survive 1462 Offsprings, try Populating to 3000 ones


  --> Evolve Generation 5 MaxIRres-7.60|MaxIRraw-5.60: 100%|██████████| 3000/3000 [06:26<00:00,  7.76it/s]


**A HallofFame(500) has been Evolutionized
**6 Generations of Evolution Done, Cost 2445.97 Secs, Freed CudaMemory 15.90G - > 15.90G
-------------------- Selection --------------------
**HallofFame(500) Contains 500 Promising Candidates with RankIR >= 3.00
  --> Hof__0/Elite356 (IR-7.65|Corr+0.00): ts_max(TURN,9)
  --> Hof_20/Elite357 (IR-6.77|Corr+0.62): add(log(TURN),ts_corr(ts_top_avg(VOL,10,6),TURN,7))
  --> Hof_21/Elite358 (IR-6.71|Corr+0.69): rank(ts_xtop_yavg(HP,TURN,10,1))
  --> Hof_25/Elite359 (IR-6.45|Corr+0.57): ts_rng_dif(RTN,15,1)
  --> Hof_37/Elite360 (IR-6.27|Corr+0.67): ts_dwdif(RTN,DP,20)
  --> Hof_51/Elite361 (IR-6.13|Corr+0.69): ma(TURN,40)
  --> Hof_54/Elite362 (IR-6.10|Corr+0.62): sigmoid(ts_xbtm_yavg(ts_top_avg(VP,20,9),ts_max(TURN,7),15,1))
  --> Hof_58/Elite363 (IR-6.06|Corr+0.66): ts_max(square(ts_dwdif(ts_dwdif(TURN,log(ADV60),15),ts_dwdif(ts_cov(dp,vp,5),pctchg(HP,40),40),15)),5)
  --> Hof_81/Elite364 (IR-5.84|Corr+0.69): ts_rng_dif(power(RTN,1.7),40,9)
  --> 

In [1]:
import gp_math_func as MF
import torch
x = torch.rand(1000,1000,3)
y = torch.rand(1000,1000)
insample = torch.arange(1000) < 700
def f1(x,y,insample=None):
    return MF.neutralize_2d(y , x)

def f2(x,y,insample):
    shape2d = y.shape
    insample = insample.reshape(-1,1).expand(shape2d)
    x = x.reshape(-1,x.shape[-1])
    y = y.reshape(-1)
    insample = insample.reshape(-1)
    y = MF.neutralize_1d(y , x , insample)
    return y.reshape(shape2d)

In [11]:
a = torch.arange(4)
b = a.reshape(2,2).clone()
b[0,0]=10
a

tensor([0, 1, 2, 3])

In [6]:
%timeit f1(x,y,insample)

275 ms ± 3.19 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit f2(x,y,insample)

28.2 ms ± 435 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
# 给定因子表达式,得到全样本区间的因子值
from gp_main import *
from gp_utils import *

func = gp_factor_generator(test_code = False)
print(func('ts_rng_dif(AMT,10,1)' , 'inf'))

**Job Directory is : "./pop/1"
-------------------- Data --------------------
**Load Data Done, Cost 2.31 Secs
**Cuda Memory: Free 12.8G, Allocated 9.2G, Reserved 10.4G, Re-collect 0.0G Cache!
tensor([[       nan,        nan,        nan,  ...,        nan,        nan,
                nan],
        [       nan,        nan,        nan,  ...,        nan,        nan,
                nan],
        [       nan,        nan,        nan,  ...,        nan,        nan,
                nan],
        ...,
        [1.4303e+09, 1.0773e+09, 1.6222e+08,  ..., 9.0968e+06, 4.0077e+07,
         2.0850e+07],
        [1.4303e+09, 1.0773e+09, 1.6222e+08,  ..., 9.9075e+06, 5.3841e+07,
         2.0982e+07],
        [1.4303e+09, 1.0773e+09, 1.6222e+08,  ..., 9.9075e+06, 5.1188e+07,
         2.0982e+07]], device='cuda:0')


In [10]:
print(func('ts_rng_dif(AMT,10,1)' , 'inf_trim_norm'))

tensor([[    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
        ...,
        [    nan,     nan,  0.0094,  ..., -0.0129, -0.0084, -0.0112],
        [    nan,     nan,  0.0098,  ..., -0.0129, -0.0063, -0.0113],
        [    nan,     nan,  0.0101,  ..., -0.0130, -0.0067, -0.0113]],
       device='cuda:0')


In [24]:
value = func('ts_corr(LP, AMT, 9)' , process_key = 'inf')
blk = func('ts_xrng_ydif(VOL,TURN,30,3)' , process_key = 'inf_norm')
MF.corrwith(value , blk , dim = 1)

tensor([0.0000, 0.0000, 0.0000,  ..., 0.0458, 0.0354, 0.0514], device='cuda:0')

In [3]:
import gp_math_func as MF
# func('ts_beta(LP, AMT, 9)' , process_key = 'inf')
LP = func('LP' , process_key = '')
AMT = func('AMT' , process_key = '')

In [8]:
MF.beta(LP[-10:] , AMT[-10:])

tensor(108359.4844, device='cuda:0')

In [6]:
MF.ts_beta(LP , AMT , 9)

tensor([[       0.0000,        0.0000,        0.0000,  ...,
                0.0000,        0.0000,        0.0000],
        [       0.0000,        0.0000,        0.0000,  ...,
                0.0000,        0.0000,        0.0000],
        [       0.0000,        0.0000,        0.0000,  ...,
                0.0000,        0.0000,        0.0000],
        ...,
        [15941960.0000,  3646614.7500,  3124203.2500,  ...,
          8444937.0000, 16713982.0000,  -614028.4375],
        [12516580.0000,  2836713.7500, 11548762.0000,  ...,
          7810983.5000, 15766038.0000,  1821985.8750],
        [12630410.0000,  2627487.0000, 10933780.0000,  ...,
          7306392.5000, 15859513.0000,  3794529.0000]], device='cuda:0')

In [ ]:
from gp_main import *
a = gp_multifactor(0)

Loading factor parquets: 100%|██████████| 5/5 [00:06<00:00,  1.21s/it]


Beware! future information used!


In [ ]:
import torch
a = torch.Tensor([torch.nan,torch.inf])
b = a.nan_to_num_(0,0,0)
a is b

True

In [3]:
import joblib
a = joblib.load('./pop/0/logbook/iter1_gen0.pkl')

In [7]:
len(a[-1]['forbidden'])

165